# Generated by Django 3.1.4 on 2021-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dreamreal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
