# Generated by Django 3.1.4 on 2021-01-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dreamreal',
            new_name='register',
        ),
    ]
