# Generated by Django 3.1.4 on 2021-01-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210115_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='user',
        ),
    ]
