# Generated by Django 3.1.4 on 2021-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210115_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='indian',
            field=models.CharField(default='t', max_length=1),
        ),
    ]
