# Generated by Django 3.1.4 on 2021-01-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_indian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='indian',
        ),
    ]
