# Generated by Django 3.1.4 on 2021-01-15 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 1, 28, 20, 611573)),
            preserve_default=False,
        ),
    ]
