codes = {'3M India': ['3MINDIA', '523395'],
 'Aarti Ind': ['AARTIIND'],
 'AAVAS Financier': ['AAVAS', '541988'],
 'AB Capital': ['Y', 'ABCAPITAL'],
 'ABB India': ['ABB', '500002'],
 'Abbott India': ['ABBOTINDIA', '500488'],
 'ACC': ['ACC', '500410'],
 'Adani Ports': ['Y', 'ADANIPORTS'],
 'Adani Power': ['ADANIPOWER', '533096'],
 'Adani Total Gas': ['ATGL', '542066'],
 'Adani Trans': ['ADANITRANS'],
 'Aditya Birla F': ['Y', 'ABFRL'],
 'Advanced Enzyme': ['Y', 'ADVENZYMES'],
 'Aegis Logistics': ['AEGISCHEM'],
 'AFL': ['Y', 'ARVINDFASN'],
 'AIA Engineering': ['AIAENG'],
 'Ajanta Pharma': ['AJANTPHARM'],
 'Akzo Nobel': ['AKZOINDIA'],
 'Alembic Pharma': ['Y', 'APLLTD'],
 'Alkem Lab': ['ALKEM'],
 'Alkyl Amines': ['ALKYLAMINE'],
 'Allcargo': ['Y', 'ALLCARGO'],
 'Amara Raja Batt': ['AMARAJABAT'],
 'Amber Enterpris': ['Y', 'AMBER'],
 'Ambuja Cements': ['AMBUJACEM'],
 'APL Apollo': ['APLAPOLLO'],
 'Apollo Hospital': ['Y', 'APOLLOHOSP'],
 'Apollo Tyres': ['APOLLOTYRE', '500877'],
 'Asahi India': ['ASAHIINDIA'],
 'Ashok Leyland': ['ASHOKLEY', '500477'],
 'Ashoka Buildcon': ['ASHOKA', '533271'],
 'Asian Paints': ['ASIANPAINT', '500820'],
 'Aster DM Health': ['ASTERDM'],
 'Astral Poly Tec': ['Y', 'ASTRAL'],
 'AstraZeneca': ['ASTRAZEN'],
 'Atul': ['ATUL', '500027'],
 'AU Small Financ': ['Y', 'AUBANK'],
 'Aurobindo Pharm': ['AUROPHARMA'],
 'Avanti Feeds': ['AVANTIFEED'],
 'Avenue Supermar': ['DMART'],
 'Axis Bank': ['AXISBANK', '532215'],
 'Bajaj Auto': ['BAJAJ-AUTO', '532977'],
 'Bajaj Consumer ': ['BAJAJCON'],
 'Bajaj Electric': ['BAJAJELEC'],
 'Bajaj Finance': ['BAJFINANCE', '500034'],
 'Bajaj Finserv': ['BAJAJFINSV'],
 'Bajaj Holdings': ['Y', 'BAJAJHLDNG'],
 'Balkrishna Ind': ['Y', 'BALKRISIND'],
 'Balmer Lawrie': ['BALMLAWRIE'],
 'Balrampur Chini': ['BALRAMCHIN'],
 'Bandhan Bank': ['BANDHANBNK'],
 'Bank of Baroda': ['BANKBARODA', '532134'],
 'Bank of India': ['BANKINDIA', '532149'],
 'Bank of Mah': ['MAHABANK'],
 'BASF': ['BASF', '500042'],
 'Bata India': ['BATAINDIA', '500043'],
 'Bayer CropScien': ['BAYERCROP'],
 'BEML': ['BEML', '500048'],
 'Berger Paints': ['Y', 'BERGEPAINT'],
 'Bharat Dynamics': ['Y', 'BDL'],
 'Bharat Elec': ['BEL', '500049'],
 'Bharat Forge': ['BHARATFORG', '500493'],
 'Bharat Rasayan': ['BHARATRAS'],
 'Bharti Airtel': ['BHARTIARTL'],
 'BHEL': ['Y', 'BHEL'],
 'Biocon': ['BIOCON', '532523'],
 'Birla Corp': ['BIRLACORPN'],
 'Birlasoft': ['BSOFT', '532400'],
 'Bliss GVS': ['BLISSGVS'],
 'Blue Dart': ['BLUEDART'],
 'Blue Star': ['BLUESTARCO', '500067'],
 'Bombay Burmah': ['Y', 'BBTC'],
 'Bombay Dyeing': ['Y', 'BOMDYEING'],
 'Bosch': ['BOSCHLTD', '500530'],
 'BPCL': ['Y', 'BPCL'],
 'Brigade Ent': ['BRIGADE'],
 'Britannia': ['BRITANNIA'],
 'BSE Limited': ['N/A', 'N/A'],
 'Cadila Health': ['CADILAHC'],
 'Can Fin Homes': ['CANFINHOME', '511196'],
 'Canara Bank': ['CANBK', '532483'],
 'Caplin Labs': ['Y', 'CAPLIPOINT'],
 'Capri Global': ['Y', 'CGCL'],
 'Carborundum': ['CARBORUNIV'],
 'CARE Ratings': ['CARERATING', '534804'],
 'Castrol': ['CASTROLIND'],
 'CCL Products': ['CCL', '519600'],
 'CDSL': [],
 'Ceat': ['CEATLTD', '500878'],
 'Central Bank': ['CENTRALBK'],
 'Century': ['Y', 'CENTURYTEX'],
 'CenturyPlyboard': ['CENTURYPLY'],
 'Cera Sanitary': ['CERA', '532443'],
 'CESC': ['CESC', '500084'],
 'CG Consumer': ['Y', 'CROMPTON'],
 'Chambal Fert': ['Y', 'CHAMBLFERT'],
 'Chennai Petro': ['Y', 'CHENNPETRO'],
 'Cholamandalam': ['Y', 'CHOLAHLDNG'],
 'Cholamandalam': ['Y', 'CHOLAFIN'],
 'Cipla': ['CIPLA', '500087'],
 'City Union Bank': ['CUB', '532210'],
 'Coal India': ['COALINDIA', '533278'],
 'Cochin Shipyard': ['COCHINSHIP'],
 'COFORGE LTD.': ['COFORGE'],
 'Colgate': ['Y', 'COLPAL'],
 'Container Corp': ['Y', 'CONCOR'],
 'Coromandel Int': ['Y', 'COROMANDEL'],
 'CreditAccess Gr': ['Y', 'CREDITACC'],
 'CRISIL': ['CRISIL', '500092'],
 'Cummins': ['CUMMINSIND'],
 'Cyient': ['CYIENT', '532175'],
 'Dabur India': ['DABUR', '500096'],
 'Dalmia Bharat': ['DALBHARAT', '542216'],
 'DB Corp': ['DBCORP', '533151'],
 'DCB Bank': ['DCBBANK', '532772'],
 'DCM Shriram': ['DCMSHRIRAM'],
 'Deepak Nitrite': ['DEEPAKNTR', '506401'],
 'Delta Corp': ['DELTACORP', '532848'],
 'Dhani Services': ['DHANI', '532960'],
 'Dhanuka Agritec': ['DHANUKA'],
 'Dilip Buildcon': ['DBL', '540047'],
 'Dish TV': ['DISHTV', '532839'],
 'Dishman Carboge': ['DCAL'],
 'Divis Labs': ['DIVISLAB'],
 'Dixon Technolog': ['DIXON'],
 'DLF': ['DLF', '532868'],
 'Dr Lal PathLab': ['LALPATHLAB'],
 'Dr Reddys Labs': ['DRREDDY'],
 'eClerx Services': ['ECLERX', '532927'],
 'Edelweiss': ['Y', 'EDELWEISS'],
 'Eicher Motors': ['EICHERMOT', '505200'],
 'EID Parry': ['EIDPARRY', '500125'],
 'EIH': ['EIHOTEL', '500840'],
 'Elgi Equipments': ['ELGIEQUIP'],
 'Emami': ['EMAMILTD', '531162'],
 'Endurance Techn': ['Y', 'ENDURANCE'],
 'EngineersInd': ['ENGINERSIN'],
 'EPL': ['EPL', '500135'],
 'Equitas Holding': ['EQUITAS'],
 'Esab India': ['ESABINDIA', '500133'],
 'Escorts': ['ESCORTS', '500495'],
 'Exide Ind': ['EXIDEIND', '500086'],
 'FDC': ['FDC', '531599'],
 'Federal Bank': ['FEDERALBNK', '500469'],
 'Fine Organics': ['Y', 'FINEORG'],
 'Finolex Cables': ['FINCABLES'],
 'Finolex Ind': ['FINPIPE', '500940'],
 'Firstsource Sol': ['Y', 'FSL'],
 'Fortis Health': ['FORTIS', '532843'],
 'Future Consumer': ['FCONSUMER'],
 'Future Retail': ['FRETAIL', '540064'],
 'GAIL': ['GAIL', '532155'],
 'Galaxy Surfacta': ['Y', 'GALAXYSURF'],
 'Garden Reach Sh': ['Y', 'GRSE'],
 'Garware Technic': ['Y', 'GARFIBRES'],
 'GE Power India': ['GEPIL', '532309'],
 'GE Shipping': ['Y', 'GESHIP'],
 'GE T&D India': ['GET&D', '522275'],
 'General Insuran': ['Y', 'GICRE'],
 'Gillette India': ['GILLETTE', '507815'],
 'GlaxoSmithKline': ['Y', 'GLAXO'],
 'Glenmark': ['GLENMARK'],
 'GMM Pfaudler': ['GMMPFAUDLR'],
 'GMR Infra': ['GMRINFRA'],
 'GNFC': ['Y', 'GNFC'],
 'Godfrey Phillip': ['GODFRYPHLP'],
 'Godrej Agrovet': ['GODREJAGRO'],
 'Godrej Consumer': ['Y', 'GODREJCP'],
 'Godrej Ind': ['GODREJIND'],
 'Godrej Prop': ['GODREJPROP'],
 'Granules India': ['GRANULES'],
 'Graphite India': ['GRAPHITE'],
 'Grasim': ['GRASIM'],
 'Greaves Cotton': ['GREAVESCOT', '501455'],
 'Grindwell Norto': ['GRINDWELL', '506076'],
 'GSFC': ['Y', 'GSFC'],
 'Guj Alkali': ['Y', 'GUJALKALI'],
 'Guj Heavy Chem': ['Y', 'GHCL'],
 'Guj Mineral': ['Y', 'GMDCLTD'],
 'Guj State Petro': ['Y', 'GSPL'],
 'Gujarat Fluoro': ['Y'],
 'Gujarat Gas': ['GUJGASLTD', '539336'],
 'Gujarat Pipavav': ['Y', 'GPPL'],
 'Gulf Oil Lubric': ['Y', 'GULFOILLUB'],
 'Hathway Cable': ['HATHWAY'],
 'Hatsun Agro': ['HATSUN'],
 'Havells India': ['HAVELLS', '517354'],
 'HCL Tech': ['HCLTECH'],
 'HDFC': ['Y', 'HDFC'],
 'HDFC AMC': ['Y', 'HDFCAMC'],
 'HDFC Bank': ['HDFCBANK', '500180'],
 'HDFC Life': ['Y', 'HDFCLIFE'],
 'HEG': ['HEG', '509631'],
 'Heidelberg Cem': ['Y', 'HEIDELBERG'],
 'Heritage Foods': ['HERITGFOOD'],
 'Hero Motocorp': ['HEROMOTOCO', '500182'],
 'Hexaware Tech': ['HEXAWARE'],
 'HFCL': ['HFCL', '500183'],
 'Himadri Special': ['Y', 'HSCL'],
 'Himatsingka Sei': ['HIMATSEIDE'],
 'Hind Copper': ['HINDCOPPER'],
 'Hind Zinc': ['HINDZINC', '500188'],
 'Hindalco': ['HINDALCO'],
 'Hindustan Aeron': ['Y', 'HAL'],
 'Honeywell Autom': ['HONAUT'],
 'HPCL': ['Y', 'HINDPETRO'],
 'HUDCO': ['Y', 'HUDCO'],
 'HUL': ['HINDUNILVR'],
 'ICICI Bank': ['ICICIBANK', '532174'],
 'ICICI Lombard ': ['Y', 'ICICIGI'],
 'ICICI Prudentia': ['Y'],
 'ICICI Securitie': ['Y', 'ISEC'],
 'ICRA': ['ICRA', '532835'],
 'IDBI Bank': ['IDBI', '500116'],
 'IDFC': ['IDFC', '532659'],
 'IDFC First Bank': ['IDFCFIRSTB'],
 'IEX': ['IEX'],
 'IFB Industries': ['IFBIND'],
 'IFCI': ['IFCI', '500106'],
 'IGL': ['IGL', '532514'],
 'IIFL Finance': ['IIFL', '532636'],
 'India Cements': ['INDIACEM', '530005'],
 'India Tourism D': ['Y', 'ITDC'],
 'Indiabulls Hsg': ['Y', 'IBULHSGFIN'],
 'Indiabulls Real': ['Y', 'IBREALEST'],
 'Indiamart Inter': ['INDIAMART'],
 'Indian Bank': ['INDIANB', '532814'],
 'Indian Hotels': ['INDHOTEL'],
 'Indoco Remedies': ['INDOCO', '532612'],
 'Indostar Capita': ['Y', 'INDOSTAR'],
 'INDUS TOWERS': ['INDUSTOWER'],
 'IndusInd Bank': ['INDUSINDBK', '532187'],
 'Infibeam Avenue': ['INFIBEAM'],
 'Info Edge': ['NAUKRI'],
 'Infosys': ['INFY', '500209'],
 'Ingersoll Rand': ['Y', 'INGERRAND'],
 'INOX Leisure': ['INOXLEISUR'],
 'Intellect Desig': ['INTELLECT'],
 'Interglobe Avi': ['INDIGO'],
 'IOB': ['IOB', '532388'],
 'IOC': ['IOC'],
 'Ipca Labs': ['IPCALAB', '524494'],
 'IRB Infra': ['Y', 'IRB'],
 'Ircon Internati': ['IRCON'],
 'IRCTC': ['Y', 'IRCTC'],
 'ITC': ['ITC', '500875'],
 'ITI': ['ITI', '523610'],
 'IWML': ['Y', 'IIFLWAM'],
 'J. K. Cement': ['JKCEMENT', '532644'],
 'JagranPrakashan': ['JAGRAN'],
 'Jai Corp': ['JAICORPLTD', '512237'],
 'Jamna Auto': ['JAMNAAUTO'],
 'JB Chemicals': ['Y', 'JBCHEPHARM'],
 'Jindal (Hisar)': ['JSLHISAR'],
 'Jindal Saw': ['JINDALSAW', '500378'],
 'Jindal Stainles': ['JSL', '532508'],
 'Jindal Steel': ['JINDALSTEL'],
 'JK Bank': ['J&KBANK'],
 'JK Lakshmi Cem': ['JKLAKSHMI'],
 'JK Paper': ['JKPAPER', '532162'],
 'JK Tyre & Ind': ['JKTYRE'],
 'JM Financial': ['JMFINANCIL', '523405'],
 'Johnson Control': ['Y'],
 'JSW Energy': ['JSWENERGY', '533148'],
 'JSW Steel': ['JSWSTEEL', '500228'],
 'Jubilant Food': ['JUBLFOOD'],
 'Jubilant Pharmo': ['JUBLPHARMA'],
 'Just Dial': ['JUSTDIAL', '535648'],
 'Jyothy Labs': ['JYOTHYLAB', '532926'],
 'Kajaria Ceramic': ['KAJARIACER'],
 'Kalpataru Power': ['Y', 'KALPATPOWR'],
 'Kansai Nerolac': ['KANSAINER'],
 'Karnataka Bank': ['KTKBANK', '532652'],
 'Karur Vysya': ['KARURVYSYA'],
 'Kaveri Seed': ['Y', 'KSCL'],
 'KEC Intl': ['KEC'],
 'KEI Industries': ['KEI', '517569'],
 'KNR Construct': ['KNRCON'],
 'Kolte-Patil': ['Y', 'KOLTEPATIL'],
 'Kotak Mahindra': ['KOTAKBANK'],
 'KPIT Tech': ['Y', 'KPITTECH'],
 'KPR Mill': ['KPRMILL', '532889'],
 'KRBL': ['KRBL', '530813'],
 'KSB Pumps': ['KSB', '500249'],
 'L&T Finance': ['L&TFH', '533519'],
 'L&T Infotech': ['Y', 'LTI'],
 'L&T Technology': ['LTTS'],
 'La Opala RG': ['LAOPALA', '526947'],
 'Lakshmi Machine': ['LAXMIMACH'],
 'Larsen': ['LT', '500510'],
 'Laurus Labs': ['LAURUSLABS', '540222'],
 'Lemon Tree Hote': ['LEMONTREE'],
 'LIC Housing Fin': ['LICHSGFIN'],
 'Linde India': ['LINDEINDIA', '523457'],
 'Lupin': ['LUPIN', '500257'],
 'Lux Industries': ['LUXIND', '539542'],
 'M&M': ['M&M', '500520'],
 'Mah Scooters': ['Y', 'MAHSCOOTER'],
 'Mah Seamless': ['Y', 'MAHSEAMLES'],
 'Mahanagar Gas': ['MGL', '539957'],
 'Mahindra CIE': ['Y', 'MAHINDCIE'],
 'Mahindra Holida': ['Y', 'MHRIL'],
 'Mahindra Logist': ['MAHLOG'],
 'Manappuram Fin': ['Y', 'MANAPPURAM'],
 'Marico': ['MARICO', '531642'],
 'Maruti Suzuki': ['MARUTI'],
 'MAS Financial S': ['Y', 'MASFIN'],
 'Max Financial': ['MFSL', '500271'],
 'MCX India': ['Y', 'MCX'],
 'Metropolis': ['Y', 'METROPOLIS'],
 'Minda Corp': ['MINDACORP'],
 'Minda Ind': ['MINDAIND'],
 'Mindtree': ['MINDTREE', '532819'],
 'Mishra Dhatu Ni': ['MIDHANI'],
 'MMTC Ltd': ['MMTC', '513377'],
 'MOIL': ['MOIL', '533286'],
 'Motherson Sumi': ['Y', 'MOTHERSUMI'],
 'Motilal Oswal': ['Y', 'MOTILALOFS'],
 'MphasiS': ['MPHASIS', '526299'],
 'MRF': ['MRF', '500290'],
 'MRPL': ['Y', 'MRPL'],
 'Muthoot Finance': ['MUTHOOTFIN'],
 'NALCO': ['Y', 'NATIONALUM'],
 'Narayana Hruda': ['NH', '539551'],
 'Natco Pharma': ['NATCOPHARM'],
 'Nava Bharat Ven': ['NBVENTURES'],
 'Navin Fluorine': ['Y', 'NAVINFLUOR'],
 'NBCC (India)': ['NBCC', '534309'],
 'NCC': ['NCC', '500294'],
 'NESCO': ['NESCO', '505355'],
 'Nestle': ['NESTLEIND', '500790'],
 'New India Assur': ['Y', 'NIACL'],
 'NFL': ['Y', 'NFL'],
 'NHPC': ['NHPC', '533098'],
 'Nilkamal': ['NILKAMAL', '523385'],
 'Nippon': ['Y', 'NAM-INDIA'],
 'NLC India': ['NLCINDIA', '513683'],
 'NMDC': ['NMDC', '526371'],
 'NTPC': [],
 'Oberoi Realty': ['OBEROIRLTY', '533273'],
 'Oil India': ['OIL', '533106'],
 'Omaxe': ['OMAXE', '532880'],
 'ONGC': ['Y', 'ONGC'],
 'Oracle Fin Serv': ['Y', 'OFSS'],
 'Orient Cement': ['ORIENTCEM'],
 'Orient Refract': ['ORIENTREF'],
 'P and G': ['Y', 'PGHH'],
 'Page Industries': ['PAGEIND'],
 'Persistent': ['PERSISTENT'],
 'Petronet LNG': ['PETRONET', '532522'],
 'Pfizer': ['PFIZER', '500680'],
 'Phillips Carbon': ['Y', 'PHILIPCARB'],
 'Phoenix Mills': ['PHOENIXLTD'],
 'PI Industries': ['PIIND', '523642'],
 'Pidilite Ind': ['PIDILITIND'],
 'Piramal Enter': ['PEL'],
 'PNB': ['Y', 'PNB'],
 'PNB Housing Fin': ['PNBHOUSING'],
 'PNC Infratech': ['PNCINFRA', '539150'],
 'Poly Medicure': ['POLYMED', '531768'],
 'Polycab': ['POLYCAB', '542652'],
 'Power Finance': ['Y', 'PFC'],
 'Power Grid Corp': ['Y', 'POWERGRID'],
 'Praj Industries': ['PRAJIND'],
 'Prestige Estate': ['Y', 'PRESTIGE'],
 'Prism Cement': ['PRSMJOHNSN', '500338'],
 'Procter&Gamble': ['PGHL'],
 'PTC India': ['PTC', '532524'],
 'PVR': ['PVR', '532689'],
 'Quess Corp': ['QUESS', '539978'],
 'Radico Khaitan': ['RADICO', '532497'],
 'Rail Vikas': ['RVNL', '542649'],
 'Rain Industries': ['RAIN', '500339'],
 'Rajesh Exports': ['RAJESHEXPO'],
 'Rallis India': ['RALLIS', '500355'],
 'Ramco Cements': ['RAMCOCEM', '500260'],
 'Rashtriya Chem': ['Y', 'RCF'],
 'Ratnamani Metal': ['RATNAMANI'],
 'Raymond': ['RAYMOND', '500330'],
 'RBL Bank': ['RBLBANK', '540065'],
 'REC': ['RECLTD', '532955'],
 'Redington': ['REDINGTON'],
 'Relaxo Footwear': ['RELAXO'],
 'Reliance': ['RELIANCE'],
 'Repco Home': ['REPCOHOME'],
 'RITES': ['RITES', '541556'],
 'Sadbhav Engg': ['SADBHAV'],
 'SAIL': ['SAIL'],
 'Sanofi India': ['SANOFI', '500674'],
 'SBI': ['SBIN', '500112'],
 'SBI Life Insura': ['Y', 'SBILIFE'],
 'Schaeffler Ind': ['SCHAEFFLER'],
 'Schneider Infra': ['Y', 'SCHNEIDER'],
 'Sequent Scienti': ['SEQUENT'],
 'Sheela Foam': ['SFL', '540203'],
 'Shipping Corp': ['Y', 'SCI'],
 'Shoppers Stop': ['SHOPERSTOP'],
 'Shree Cements': ['SHREECEM', '500387'],
 'Shree Renuka': ['Y', 'RENUKA'],
 'Shriram City': ['Y', 'SHRIRAMCIT'],
 'Shriram Trans': ['Y', 'SRTRANSFIN'],
 'Siemens': ['SIEMENS', '500550'],
 'SIS': ['SIS', '540673'],
 'SJVN': ['SJVN', '533206'],
 'SKF India': ['SKFINDIA', '500472'],
 'Sobha': ['SOBHA', '532784'],
 'Solar Ind': ['Y', 'SOLARINDS'],
 'Sonata': ['SONATSOFTW'],
 'South Ind Bk': ['SOUTHBANK'],
 'SpiceJet': ['SPICEJET', '500285'],
 'SRF': ['SRF', '503806'],
 'Star Cement': ['STARCEMENT'],
 'Sterlite Techno': ['Y', 'STLTECH'],
 'Strides Pharma ': ['Y', 'STAR'],
 'Sudarshan Chem': ['Y', 'SUDARSCHEM'],
 'SUMITOMO': ['Y'],
 'Sun Pharma': ['Y', 'SUNPHARMA'],
 'Sun Pharma Adv': ['Y', 'SPARC'],
 'Sun TV Network': ['SUNTV', '532733'],
 'Sundaram Fin': ['SUNDARMFIN'],
 'Sundram': ['SUNDRMFAST'],
 'Sunteck Realty': ['SUNTECK', '512179'],
 'Suprajit Eng': ['Y', 'SUPRAJIT'],
 'Supreme Ind': ['SUPREMEIND'],
 'Suzlon Energy': ['SUZLON', '532667'],
 'Swan Energy': ['SWANENERGY', '503310'],
 'Symphony': ['SYMPHONY', '517385'],
 'Syngene Intl': ['Y', 'SYNGENE'],
 'Tasty Bite': ['TASTYBITE'],
 'Tata Comm': ['TATACOMM'],
 'TATA Cons. Prod': ['TATACONSUM'],
 'Tata Elxsi': ['TATAELXSI', '500408'],
 'Tata Inv Corp': ['Y', 'TATAINVEST'],
 'Tata Motors': ['TATAMOTORS', '500570'],
 'Tata Power': ['TATAPOWER'],
 'Tata Steel': ['TATASTEEL', '500470'],
 'Tata Steel BSL ': ['TATASTLBSL'],
 'TCNS Clothing C': ['TCNSBRANDS'],
 'TCS': ['Y', 'TCS'],
 'TeamLease Ser.': ['TEAMLEASE'],
 'Tech Mahindra': ['TECHM', '532755'],
 'Thermax': ['THERMAX', '500411'],
 'Thyrocare Techn': ['Y', 'THYROCARE'],
 'Time Techno': ['TIMETECHNO'],
 'Timken': ['TIMKEN', '522113'],
 'Titan Company': ['TITAN', '500114'],
 'TML-D': ['Y', 'TATAMTRDVR'],
 'Torrent Pharma': ['Y', 'TORNTPHARM'],
 'Torrent Power': ['TORNTPOWER'],
 'Trent': ['TRENT', '500251'],
 'Trident': ['TRIDENT', '521064'],
 'TTK Prestige': ['TTKPRESTIG'],
 'TV TodayNetwork': ['TVTODAY', '532515'],
 'TV18 Broadcast': ['TV18BRDCST'],
 'TVS Motor': ['TVSMOTOR'],
 'UCO Bank': ['UCOBANK', '532505'],
 'Uflex': ['UFLEX', '500148'],
 'Ujjivan Financi': ['Y', 'UJJIVAN'],
 'UltraTechCement': ['ULTRACEMCO'],
 'Union Bank': ['UNIONBANK'],
 'United Brewerie': ['UBL', '532478'],
 'United Spirits': ['MCDOWELL-N'],
 'UPL': ['UPL', '512070'],
 'V-Guard Ind': ['VGUARD'],
 'V-Mart Retail': ['VMART', '534976'],
 'Vaibhav Global': ['VAIBHAVGBL'],
 'Vakrangee': ['VAKRANGEE', '511431'],
 'Vardhman Text': ['VTL', '502986'],
 'Varroc Engineer': ['VARROC'],
 'Varun Beverages': ['VBL', '540180'],
 'Vedanta': ['VEDL', '500295'],
 'Venkys': ['VENKEYS', '523261'],
 'Vesuvius India': ['VESUVIUS'],
 'Vinati Organics': ['VINATIORGA'],
 'VIP Industries': ['VIPIND', '507880'],
 'Vodafone Idea': ['IDEA'],
 'Voltas': ['VOLTAS', '500575'],
 'VRL Logistics': ['VRLLOG', '539118'],
 'VST': ['VSTIND', '509966'],
 'WABCO India': ['WABCOINDIA', '533023'],
 'Welspun Corp': ['WELCORP', '532144'],
 'Welspun India': ['WELSPUNIND'],
 'Westlife Dev': ['WESTLIFE'],
 'Whirlpool': ['WHIRLPOOL', '500238'],
 'Wipro': ['WIPRO', '507685'],
 'Wockhardt': ['WOCKPHARMA', '532300'],
 'Zee Entertain': ['Y', 'ZEEL'],
 'Zensar Tech': ['ZENSARTECH'],
 'Zydus Wellness': ['ZYDUSWELL']}