href_dic = {'3M India': '/india/stockpricequote/diversified/3mindia/MI42',
 'Aarti Ind': '/india/stockpricequote/chemicals/aartiindustries/AI45',
 'AAVAS Financier': '/india/stockpricequote/financegeneral/aavasfinanciers/AF17',
 'AB Capital': '/india/stockpricequote/financeinvestments/adityabirlacapital/ABC9',
 'ABB India': '/india/stockpricequote/infrastructuregeneral/abbindia/ABB',
 'Abbott India': '/india/stockpricequote/pharmaceuticals/abbottindia/AI51',
 'ACC': '/india/stockpricequote/cementmajor/acc/ACC06',
 'Adani Ports': '/india/stockpricequote/infrastructuregeneral/adaniportsspecialeconomiczone/MPS',
 'Adani Power': '/india/stockpricequote/powergenerationdistribution/adanipower/AP11',
 'Adani Total Gas': '/india/stockpricequote/gasdistribution/adanitotalgas/ADG01',
 'Adani Trans': '/india/stockpricequote/powertransmissionequipment/adanitransmission/AT22',
 'Aditya Birla F': '/india/stockpricequote/retail/adityabirlafashionretail/PFR',
 'Advanced Enzyme': '/india/stockpricequote/pharmaceuticals/advancedenzymetechnologies/AET',
 'Aegis Logistics': '/india/stockpricequote/transportlogistics/aegislogistics/AL9',
 'AFL': '/india/stockpricequote/miscellaneous/arvindfashionslimited/ARVIN54248',
 'AIA Engineering': '/india/stockpricequote/castingsforgings/aiaengineering/AIE01',
 'Ajanta Pharma': '/india/stockpricequote/pharmaceuticals/ajantapharma/AP22',
 'Akzo Nobel': '/india/stockpricequote/paintsvarnishes/akzonobelindia/ICI',
 'Alembic Pharma': '/india/stockpricequote/pharmaceuticals/alembicpharmaceuticals/AP35',
 'Alkem Lab': '/india/stockpricequote/pharmaceuticals/alkemlaboratories/AL05',
 'Alkyl Amines': '/india/stockpricequote/chemicals/alkylamineschemicals/AAC',
 'Allcargo': '/india/stockpricequote/transportlogistics/allcargologistics/AGL02',
 'Amara Raja Batt': '/india/stockpricequote/autoancillaries/amararajabatteries/ARB',
 'Amber Enterpris': '/india/stockpricequote/miscellaneous/amberenterprisesindialimited/AEI01',
 'Ambuja Cements': '/india/stockpricequote/cementmajor/ambujacements/AC18',
 'APL Apollo': '/india/stockpricequote/steeltubespipes/aplapollotubes/BT09',
 'Apollo Hospital': '/india/stockpricequote/hospitalsmedicalservices/apollohospitalsenterprises/AHE',
 'Apollo Tyres': '/india/stockpricequote/tyres/apollotyres/AT14',
 'Asahi India': '/india/stockpricequote/glassglassproducts/asahiindiaglass/AIG01',
 'Ashok Leyland': '/india/stockpricequote/autolcvshcvs/ashokleyland/AL',
 'Ashoka Buildcon': '/india/stockpricequote/constructioncontractingcivil/ashokabuildcon/AB',
 'Asian Paints': '/india/stockpricequote/paintsvarnishes/asianpaints/AP31',
 'Aster DM Health': '/india/stockpricequote/diversified/asterdmhealthcareltd/ADH',
 'Astral Poly Tec': '/india/stockpricequote/plastics/astralpolytechnik/APT02',
 'AstraZeneca': '/india/stockpricequote/pharmaceuticals/astrazenecapharma/AZP',
 'Atul': '/india/stockpricequote/chemicals/atul/A06',
 'AU Small Financ': '/india/stockpricequote/banksprivatesector/ausmallfinancebank/ASF02',
 'Aurobindo Pharm': '/india/stockpricequote/pharmaceuticals/aurobindopharma/AP',
 'Avanti Feeds': '/india/stockpricequote/aquaculture/avantifeeds/AF21',
 'Avenue Supermar': '/india/stockpricequote/retail/avenuesupermarts/AS19',
 'Axis Bank': '/india/stockpricequote/banksprivatesector/axisbank/AB16',
 'Bajaj Auto': '/india/stockpricequote/auto23wheelers/bajajauto/BA10',
 'Bajaj Consumer ': '/india/stockpricequote/personalcare/bajajconsumercare/BC02',
 'Bajaj Electric': '/india/stockpricequote/domesticappliances/bajajelectricals/BE',
 'Bajaj Finance': '/india/stockpricequote/financeleasinghirepurchase/bajajfinance/BAF',
 'Bajaj Finserv': '/india/stockpricequote/financeinvestments/bajajfinserv/BF04',
 'Bajaj Holdings': '/india/stockpricequote/financeinvestments/bajajholdingsinvestment/BHI',
 'Balkrishna Ind': '/india/stockpricequote/tyres/balkrishnaindustries/BI03',
 'Balmer Lawrie': '/india/stockpricequote/diversified/balmerlawriecompany/BLC',
 'Balrampur Chini': '/india/stockpricequote/sugar/balrampurchinimills/BCM',
 'Bandhan Bank': '/india/stockpricequote/banksprivatesector/bandhanbank/BB09',
 'Bank of Baroda': '/india/stockpricequote/bankspublicsector/bankofbaroda/BOB',
 'Bank of India': '/india/stockpricequote/bankspublicsector/bankofindia/BOI',
 'Bank of Mah': '/india/stockpricequote/bankspublicsector/bankmaharashtra/BM05',
 'BASF': '/india/stockpricequote/chemicals/basfindia/BAS',
 'Bata India': '/india/stockpricequote/leatherproducts/bataindia/BI01',
 'Bayer CropScien': '/india/stockpricequote/pesticidesagrochemicals/bayercropscience/BC12',
 'BEML': '/india/stockpricequote/infrastructuregeneral/beml/BEM03',
 'Berger Paints': '/india/stockpricequote/paintsvarnishes/bergerpaintsindia/BPI02',
 'Bharat Dynamics': '/india/stockpricequote/miscellaneous/bharatdynamicsltd/BDL01',
 'Bharat Elec': '/india/stockpricequote/electricals/bharatelectronics/BE03',
 'Bharat Forge': '/india/stockpricequote/castingsforgings/bharatforge/BF03',
 'Bharat Rasayan': '/india/stockpricequote/pesticidesagrochemicals/bharatrasayan/BR01',
 'Bharti Airtel': '/india/stockpricequote/telecommunicationsservice/bhartiairtel/BA08',
 'BHEL': '/india/stockpricequote/infrastructuregeneral/bharatheavyelectricals/BHE',
 'Biocon': '/india/stockpricequote/pharmaceuticals/biocon/BL03',
 'Birla Corp': '/india/stockpricequote/cementmajor/birlacorporation/BC07',
 'Birlasoft': '/india/stockpricequote/computerssoftwaremediumsmall/birlasoft/KPI02',
 'Bliss GVS': '/india/stockpricequote/pharmaceuticals/blissgvspharma/BGV',
 'Blue Dart': '/india/stockpricequote/couriers/bluedartexpress/BDE',
 'Blue Star': '/india/stockpricequote/consumergoodswhitegoods/bluestar/BS',
 'Bombay Burmah': '/india/stockpricequote/plantationsteacoffee/bombayburmahtradingcorporation/BBT',
 'Bombay Dyeing': '/india/stockpricequote/textilesprocessing/bombaydyeingmanufacturingcompany/BDM',
 'Bosch': '/india/stockpricequote/autoancillaries/bosch/B05',
 'BPCL': '/india/stockpricequote/refineries/bharatpetroleumcorporation/BPC',
 'Brigade Ent': '/india/stockpricequote/constructioncontractingrealestate/brigadeenterprises/BE08',
 'Britannia': '/india/stockpricequote/foodprocessing/britanniaindustries/BI',
 'BSE Limited': '/india/stockpricequote///B08',
 'Cadila Health': '/india/stockpricequote/pharmaceuticals/cadilahealthcare/CHC',
 'Can Fin Homes': '/india/stockpricequote/financehousing/canfinhomes/CFH',
 'Canara Bank': '/india/stockpricequote/bankspublicsector/canarabank/CB06',
 'Caplin Labs': '/india/stockpricequote/pharmaceuticals/caplinpointlaboratories/CPL',
 'Capri Global': '/india/stockpricequote/financegeneral/capriglobalcapital/MMF05',
 'Carborundum': '/india/stockpricequote/abrasives/carborundumuniversal/CU',
 'CARE Ratings': '/india/stockpricequote/miscellaneous/careratings/CAR',
 'Castrol': '/india/stockpricequote/lubricants/castrolindia/CI01',
 'CCL Products': '/india/stockpricequote/plantationsteacoffee/cclproductsindia/CC10',
 'CDSL': '/india/stockpricequote///CDS',
 'Ceat': '/india/stockpricequote/tyres/ceat/C07',
 'Central Bank': '/india/stockpricequote/bankspublicsector/centralbankindia/CBO01',
 'Century': '/india/stockpricequote/diversified/centurytextilesindustries/CTI',
 'CenturyPlyboard': '/india/stockpricequote/miscellaneous/centuryplyboards/CP9',
 'Cera Sanitary': '/india/stockpricequote/ceramicsgranite/cerasanitaryware/CS18',
 'CESC': '/india/stockpricequote/powergenerationdistribution/cesc/CES',
 'CG Consumer': '/india/stockpricequote/electricals/cromptongreavesconsumerelectrical/CGC01',
 'Chambal Fert': '/india/stockpricequote/fertilisers/chambalfertiliserschemicals/CFC',
 'Chennai Petro': '/india/stockpricequote/refineries/chennaipetroleumcorporation/CPC02',
 'Cholamandalam (Finance Term Lending)': '/india/stockpricequote/miscellaneous/cholamandalamfinancialholdings/TII',
 'Cholamandalam (Finance-Investment)': '/india/stockpricequote/financeleasinghirepurchase/cholamandalaminvestmentfinancecompany/CDB',
 'Cipla': '/india/stockpricequote/pharmaceuticals/cipla/C',
 'City Union Bank': '/india/stockpricequote/banksprivatesector/cityunionbank/CUB',
 'Coal India': '/india/stockpricequote/miningminerals/coalindia/CI11',
 'Cochin Shipyard': '/india/stockpricequote/miscellaneous/cochinshipyard/CS',
 'COFORGE LTD.': '/india/stockpricequote/computerssoftware/coforgelimited/NII02',
 'Colgate': '/india/stockpricequote/personalcare/colgatepalmoliveindia/CPI',
 'Container Corp': '/india/stockpricequote/transportlogistics/containercorporationindia/CCI',
 'Coromandel Int': '/india/stockpricequote/fertilisers/coromandelinternational/CI45',
 'CreditAccess Gr': '/india/stockpricequote/financetermlendinginstitutions/creditaccessgrameen/CG03',
 'CRISIL': '/india/stockpricequote/miscellaneous/crisil/CRI',
 'Cummins': '/india/stockpricequote/engines/cumminsindia/CI02',
 'Cyient': '/india/stockpricequote/computerssoftware/cyient/IE07',
 'Dabur India': '/india/stockpricequote/personalcare/daburindia/DI',
 'Dalmia Bharat': '/india/stockpricequote/cementmajor/dalmiabharat/OCL',
 'DB Corp': '/india/stockpricequote/mediaentertainment/dbcorp/C13',
 'DCB Bank': '/india/stockpricequote/banksprivatesector/dcbbank/DCB01',
 'DCM Shriram': '/india/stockpricequote/diversified/dcmshriram/DCM02',
 'Deepak Nitrite': '/india/stockpricequote/chemicals/deepaknitrite/DN',
 'Delta Corp': '/india/stockpricequote/constructioncontractingrealestate/deltacorp/DC11',
 'Dhani Services': '/india/stockpricequote/financeinvestments/dhaniservices/IS13',
 'Dhanuka Agritec': '/india/stockpricequote/pesticidesagrochemicals/dhanukaagritech/DA01',
 'Dilip Buildcon': '/india/stockpricequote/constructioncontractingcivil/dilipbuildcon/DB04',
 'Dish TV': '/india/stockpricequote/mediaentertainment/dishtvindia/DTV',
 'Dishman Carboge': '/india/stockpricequote/miscellaneous/dishmancarbogenamcis/DCA',
 'Divis Labs': '/india/stockpricequote/pharmaceuticals/divislaboratories/DL03',
 'Dixon Technolog': '/india/stockpricequote/electricals/dixontechnologies/DT07',
 'DLF': '/india/stockpricequote/constructioncontractingrealestate/dlf/D04',
 'Dr Lal PathLab': '/india/stockpricequote/pharmaceuticals/drlalpathlabs/DLP01',
 'Dr Reddys Labs': '/india/stockpricequote/pharmaceuticals/drreddyslaboratories/DRL',
 'eClerx Services': '/india/stockpricequote/computerssoftwaremediumsmall/eclerxservices/eS06',
 'Edelweiss': '/india/stockpricequote/financegeneral/edelweissfinancialservices/EC01',
 'Eicher Motors': '/india/stockpricequote/autolcvshcvs/eichermotors/EM',
 'EID Parry': '/india/stockpricequote/sugar/eidparryindia/EID',
 'EIH': '/india/stockpricequote/hotels/eih/EIH',
 'Elgi Equipments': '/india/stockpricequote/compressors/elgiequipments/EE01',
 'Emami': '/india/stockpricequote/personalcare/emami/E06',
 'Endurance Techn': '/india/stockpricequote/auto23wheelers/endurancetechnologies/ET01',
 'EngineersInd': '/india/stockpricequote/infrastructuregeneral/engineersindia/EI14',
 'EPL': '/india/stockpricequote/packaging/epl/EP11',
 'Equitas Holding': '/india/stockpricequote/financegeneral/equitasholdings/EH03',
 'Esab India': '/india/stockpricequote/electrodesgraphite/esabindia/EI06',
 'Escorts': '/india/stockpricequote/autotractors/escorts/E',
 'Exide Ind': '/india/stockpricequote/autoancillaries/exideindustries/EI',
 'FDC': '/india/stockpricequote/pharmaceuticals/fdc/FDC',
 'Federal Bank': '/india/stockpricequote/banksprivatesector/federalbank/FB',
 'Fine Organics': '/india/stockpricequote/miscellaneous/fineorganicsindustries/FOI',
 'Finolex Cables': '/india/stockpricequote/cablestelephone/finolexcables/FC01',
 'Finolex Ind': '/india/stockpricequote/petrochemicals/finolexindustries/FI',
 'Firstsource Sol': '/india/stockpricequote/computerssoftwaremediumsmall/firstsourcesolutions/FS07',
 'Fortis Health': '/india/stockpricequote/hospitalsmedicalservices/fortishealthcare/FH',
 'Future Consumer': '/india/stockpricequote/foodprocessing/futureconsumer/FVI',
 'Future Retail': '/india/stockpricequote/retail/futureretail/FR',
 'GAIL': '/india/stockpricequote/oildrillingandexploration/gailindia/GAI',
 'Galaxy Surfacta': '/india/stockpricequote/miscellaneous/galaxysurfactantsltd/GSL06',
 'Garden Reach Sh': '/india/stockpricequote/engineeringheavy/gardenreachshipbuildersengineers/GRS01',
 'Garware Technic': '/india/stockpricequote/textilesgeneral/garwaretechnicalfibres/GWR',
 'GE Power India': '/india/stockpricequote/powertransmissionequipment/gepowerindia/AP29',
 'GE Shipping': '/india/stockpricequote/shipping/greateasternshippingcompany/GES',
 'GE T&D India': '/india/stockpricequote/powertransmissionequipment/getdindia/ATD',
 'General Insuran': '/india/stockpricequote/diversified/generalinsurancecorporationindia/GIC12',
 'Gillette India': '/india/stockpricequote/personalcare/gilletteindia/GI22',
 'GlaxoSmithKline': '/india/stockpricequote/pharmaceuticals/glaxosmithklinepharmaceuticals/GSK',
 'Glenmark': '/india/stockpricequote/pharmaceuticals/glenmarkpharma/GP08',
 'GMM Pfaudler': '/india/stockpricequote/engineeringheavy/gmmpfaudler/GMM01',
 'GMR Infra': '/india/stockpricequote/infrastructuregeneral/gmrinfrastructure/GI27',
 'GNFC': '/india/stockpricequote/fertilisers/gujaratnarmadavalleyfertilizerschemicals/GNV',
 'Godfrey Phillip': '/india/stockpricequote/cigarettes/godfreyphillipsindia/GPI',
 'Godrej Agrovet': '/india/stockpricequote/miscellaneous/godrejagrovet/GA03',
 'Godrej Consumer': '/india/stockpricequote/personalcare/godrejconsumerproducts/GCP',
 'Godrej Ind': '/india/stockpricequote/personalcare/godrejindustries/GI23',
 'Godrej Prop': '/india/stockpricequote/constructioncontractingrealestate/godrejproperties/GP11',
 'Granules India': '/india/stockpricequote/pharmaceuticals/granulesindia/GI25',
 'Graphite India': '/india/stockpricequote/electrodesgraphite/graphiteindia/GI13',
 'Grasim': '/india/stockpricequote/diversified/grasimindustries/GI01',
 'Greaves Cotton': '/india/stockpricequote/engines/greavescotton/GC20',
 'Grindwell Norto': '/india/stockpricequote/abrasives/grindwellnorton/GN',
 'GSFC': '/india/stockpricequote/fertilisers/gujaratstatefertilizerschemicals/GSF',
 'Guj Alkali': '/india/stockpricequote/chemicals/gujaratalkalieschemicals/GAC01',
 'Guj Heavy Chem': '/india/stockpricequote/chemicals/gujaratheavychemicals/GHC',
 'Guj Mineral': '/india/stockpricequote/miningminerals/gujaratmineraldevelopmentcorporation/GMD',
 'Guj State Petro': '/india/stockpricequote/oildrillingandexploration/gujaratstatepetronet/GSP02',
 'Gujarat Fluoro': '/india/stockpricequote/chemicals/gujaratfluorochemicalslimited/GUJAR54281',
 'Gujarat Gas': '/india/stockpricequote/oildrillingandexploration/gujaratgas/GGC',
 'Gujarat Pipavav': '/india/stockpricequote/shipping/gujaratpipavavport/GPP03',
 'Gulf Oil Lubric': '/india/stockpricequote/lubricants/gulfoillubricantsindia/GOL01',
 'Hathway Cable': '/india/stockpricequote/mediaentertainment/hathwaycabledatacom/HCD',
 'Hatsun Agro': '/india/stockpricequote/foodprocessing/hatsunagroproducts/HAP',
 'Havells India': '/india/stockpricequote/electricequipment/havellsindia/HI01',
 'HCL Tech': '/india/stockpricequote/computerssoftware/hcltechnologies/HCL02',
 'HDFC': '/india/stockpricequote/financehousing/housingdevelopmentfinancecorporation/HDF',
 'HDFC AMC': '/india/stockpricequote/financeinvestments/hdfcassetmanagementcompany/HAM02',
 'HDFC Bank': '/india/stockpricequote/banksprivatesector/hdfcbank/HDF01',
 'HDFC Life': '/india/stockpricequote/miscellaneous/hdfclifeinsurancecompanylimited/HSL01',
 'HEG': '/india/stockpricequote/electrodesgraphite/heg/HEG',
 'Heidelberg Cem': '/india/stockpricequote/cementmajor/heidelbergcementindia/HCI02',
 'Heritage Foods': '/india/stockpricequote/foodprocessing/heritagefoods/HFI',
 'Hero Motocorp': '/india/stockpricequote/auto23wheelers/heromotocorp/HHM',
 'Hexaware Tech': '/india/stockpricequote/computerssoftware/hexawaretechnologies/HT02',
 'HFCL': '/india/stockpricequote/telecommunicationsequipment/hfcl/HFC',
 'Himadri Special': '/india/stockpricequote/chemicals/himadrispecialitychemical/HCI01',
 'Himatsingka Sei': '/india/stockpricequote/textilessyntheticsilk/himatsingkaseide/HS',
 'Hind Copper': '/india/stockpricequote/metalsnonferrous/hindustancopper/HC07',
 'Hind Zinc': '/india/stockpricequote/metalsnonferrous/hindustanzinc/HZ',
 'Hindalco': '/india/stockpricequote/aluminium/hindalcoindustries/HI',
 'Hindustan Aeron': '/india/stockpricequote/diversified/hindustanaeronauticsltd/HAL',
 'Honeywell Autom': '/india/stockpricequote/telecommunicationsequipment/honeywellautomation/HA04',
 'HPCL': '/india/stockpricequote/refineries/hindustanpetroleumcorporation/HPC',
 'HUDCO': '/india/stockpricequote/constructioncontractingrealestate/housingurbandevelopmentcorporation/HUD',
 'HUL': '/india/stockpricequote/personalcare/hindustanunilever/HU',
 'ICICI Bank': '/india/stockpricequote/banksprivatesector/icicibank/ICI02',
 'ICICI Lombard ': '/india/stockpricequote/diversified/icicilombardgeneralinsurancecompany/ILG',
 'ICICI Prudentia': '/india/stockpricequote/financegeneral/iciciprudentiallifeinsurancecompany/IPL01',
 'ICICI Securitie': '/india/stockpricequote/miscellaneous/icicisecuritiesltd/ISL04',
 'ICRA': '/india/stockpricequote/miscellaneous/icra/ICR',
 'IDBI Bank': '/india/stockpricequote/bankprivate/idbibank/IDB05',
 'IDFC': '/india/stockpricequote/financetermlendinginstitutions/idfc/IDF',
 'IDFC First Bank': '/india/stockpricequote/banksprivatesector/idfcfirstbank/IDF01',
 'IEX': '/india/stockpricequote/diversified/indianenergyexchange/IEE',
 'IFB Industries': '/india/stockpricequote/consumergoodswhitegoods/ifbindustries/IFB02',
 'IFCI': '/india/stockpricequote/financetermlendinginstitutions/ifci/IFC02',
 'IGL': '/india/stockpricequote/oildrillingandexploration/indraprasthagas/IG04',
 'IIFL Finance': '/india/stockpricequote/financegeneral/iiflfinance/II15',
 'India Cements': '/india/stockpricequote/cementmajor/indiacements/IC',
 'India Tourism D': '/india/stockpricequote/hotels/indiatourismdevelopmentcorporation/ITD02',
 'Indiabulls Hsg': '/india/stockpricequote/financehousing/indiabullshousingfinance/IHF01',
 'Indiabulls Real': '/india/stockpricequote/constructioncontractingrealestate/indiabullsrealestate/IRE01',
 'Indiamart Inter': '/india/stockpricequote/miscellaneous/indiamartintermesh/II12',
 'Indian Bank': '/india/stockpricequote/bankspublicsector/indianbank/IB04',
 'Indian Hotels': '/india/stockpricequote/hotels/indianhotelscompany/IHC',
 'Indoco Remedies': '/india/stockpricequote/pharmaceuticals/indocoremedies/IR05',
 'Indostar Capita': '/india/stockpricequote/financegeneral/indostarcapitalfinance/ICF',
 'INDUS TOWERS': '/india/stockpricequote/telecommunicationsequipment/industowers/BI14',
 'IndusInd Bank': '/india/stockpricequote/banksprivatesector/indusindbank/IIB',
 'Infibeam Avenue': '/india/stockpricequote/miscellaneous/infibeamavenues/IIL03',
 'Info Edge': '/india/stockpricequote/miscellaneous/infoedgeindia/IEI01',
 'Infosys': '/india/stockpricequote/computerssoftware/infosys/IT',
 'Ingersoll Rand': '/india/stockpricequote/compressors/ingersollrandindia/IRI01',
 'INOX Leisure': '/india/stockpricequote/mediaentertainment/inoxleisure/INO01',
 'Intellect Desig': '/india/stockpricequote/computerssoftware/intellectdesignarena/IDA',
 'Interglobe Avi': '/india/stockpricequote/transportlogistics/interglobeaviation/IA04',
 'IOB': '/india/stockpricequote/bankspublicsector/indianoverseasbank/IOB',
 'IOC': '/india/stockpricequote/refineries/indianoilcorporation/IOC',
 'Ipca Labs': '/india/stockpricequote/pharmaceuticals/ipcalaboratories/IL',
 'IRB Infra': '/india/stockpricequote/infrastructuregeneral/irbinfrastructuredevelopers/IID01',
 'Ircon Internati': '/india/stockpricequote/engineeringheavy/irconinternational/II07',
 'IRCTC': '/india/stockpricequote/miscellaneous/irctcindianrailwaycateringtourismcorp/IRC',
 'ITC': '/india/stockpricequote/cigarettes/itc/ITC',
 'ITI': '/india/stockpricequote/telecommunicationsequipment/iti/ITI',
 'IWML': '/india/stockpricequote/miscellaneous/iiflwealthmanagementlimited/IIFLW54277',
 'J. K. Cement': '/india/stockpricequote/cementmajor/jkcement/JKC03',
 'JagranPrakashan': '/india/stockpricequote/mediaentertainment/jagranprakashan/JP12',
 'Jai Corp': '/india/stockpricequote/steelgpgcsheets/jaicorp/JC08',
 'Jamna Auto': '/india/stockpricequote/autoancillaries/jamnaautoindustries/JAI',
 'JB Chemicals': '/india/stockpricequote/pharmaceuticals/jbchemicalspharmaceuticals/JBC01',
 'Jindal (Hisar)': '/india/stockpricequote/steellarge/jindalstainlesshisar/JSH',
 'Jindal Saw': '/india/stockpricequote/steeltubespipes/jindalsaw/JS08',
 'Jindal Stainles': '/india/stockpricequote/steelmediumsmall/jindalstainless/JSL01',
 'Jindal Steel': '/india/stockpricequote/steelspongeiron/jindalsteelpower/JSP',
 'JK Bank': '/india/stockpricequote/banksprivatesector/jammukashmirbank/JKB',
 'JK Lakshmi Cem': '/india/stockpricequote/cementmajor/jklakshmicement/JKL01',
 'JK Paper': '/india/stockpricequote/paper/jkpaper/JKP01',
 'JK Tyre & Ind': '/india/stockpricequote/tyres/jktyreindustries/JKT01',
 'JM Financial': '/india/stockpricequote/financeinvestments/jmfinancial/JMF',
 'Johnson Control': '/india/stockpricequote/consumergoodswhitegoods/johnsoncontrolshitachiairconditioningindia/HHL',
 'JSW Energy': '/india/stockpricequote/powergenerationdistribution/jswenergy/JE01',
 'JSW Steel': '/india/stockpricequote/steellarge/jswsteel/JSW01',
 'Jubilant Food': '/india/stockpricequote/miscellaneous/jubilantfoodworks/JF04',
 'Jubilant Pharmo': '/india/stockpricequote/pharmaceuticals/jubilantpharmova/JO03',
 'Just Dial': '/india/stockpricequote/miscellaneous/justdial/JD',
 'Jyothy Labs': '/india/stockpricequote/personalcare/jyothylabs/JL',
 'Kajaria Ceramic': '/india/stockpricequote/ceramicsgranite/kajariaceramics/KC06',
 'Kalpataru Power': '/india/stockpricequote/powertransmissionequipment/kalpatarupowertransmission/KPT',
 'Kansai Nerolac': '/india/stockpricequote/paintsvarnishes/kansainerolacpaints/KNP',
 'Karnataka Bank': '/india/stockpricequote/banksprivatesector/karnatakabank/KB04',
 'Karur Vysya': '/india/stockpricequote/banksprivatesector/karurvysyabank/KVB',
 'Kaveri Seed': '/india/stockpricequote/miscellaneous/kaveriseedcompany/KSC01',
 'KEC Intl': '/india/stockpricequote/powertransmissionequipment/kecinternational/KEC04',
 'KEI Industries': '/india/stockpricequote/cablespowerothers/keiindustries/KEI',
 'KNR Construct': '/india/stockpricequote/constructioncontractingcivil/knrconstructions/KC13',
 'Kolte-Patil': '/india/stockpricequote/constructioncontractingrealestate/koltepatildevelopers/KD07',
 'Kotak Mahindra': '/india/stockpricequote/banksprivatesector/kotakmahindrabank/KMB',
 'KPIT Tech': '/india/stockpricequote/itservicesconsulting/kpittechnologies/KPITT54265',
 'KPR Mill': '/india/stockpricequote/textilesreadymadeapparels/kprmill/M15',
 'KRBL': '/india/stockpricequote/foodprocessing/krbl/KRB01',
 'KSB Pumps': '/india/stockpricequote/pumps/ksb/KSB',
 'L&T Finance': '/india/stockpricequote/financeinvestments/ltfinanceholdings/LFH',
 'L&T Infotech': '/india/stockpricequote/computerssoftware/larsentoubroinfotech/LI12',
 'L&T Technology': '/india/stockpricequote/computerssoftware/lttechnologyservices/LTS',
 'La Opala RG': '/india/stockpricequote/glassglassproducts/laopalarg/LOR',
 'Lakshmi Machine': '/india/stockpricequote/textilesmachinery/lakshmimachineworks/LMW',
 'Larsen': '/india/stockpricequote/infrastructuregeneral/larsentoubro/LT',
 'Laurus Labs': '/india/stockpricequote/pharmaceuticals/lauruslabs/LL05',
 'Lemon Tree Hote': '/india/stockpricequote/hotels/lemontreehotelsltd/LTH',
 'LIC Housing Fin': '/india/stockpricequote/financehousing/lichousingfinance/LIC',
 'Linde India': '/india/stockpricequote/chemicals/lindeindia/BOC',
 'Lupin': '/india/stockpricequote/pharmaceuticals/lupin/L',
 'Lux Industries': '/india/stockpricequote/textilesprocessing/luxindustries/LHI',
 'M&M': '/india/stockpricequote/autocarsjeeps/mahindramahindra/MM',
 'Mah Scooters': '/india/stockpricequote/auto23wheelers/maharashtrascooters/MS01',
 'Mah Seamless': '/india/stockpricequote/steeltubespipes/maharashtraseamless/MS02',
 'Mahanagar Gas': '/india/stockpricequote/refineries/mahanagargas/MG02',
 'Mahindra CIE': '/india/stockpricequote/castingsforgings/mahindracieautomotive/MF19',
 'Mahindra Holida': '/india/stockpricequote/hotels/mahindraholidaysresortsindia/MHR',
 'Mahindra Logist': '/india/stockpricequote/diversified/mahindralogistics/ML04',
 'Manappuram Fin': '/india/stockpricequote/financeleasinghirepurchase/manappuramfinance/MGF01',
 'Marico': '/india/stockpricequote/personalcare/marico/M13',
 'Maruti Suzuki': '/india/stockpricequote/autocarsjeeps/marutisuzukiindia/MS24',
 'MAS Financial S': '/india/stockpricequote/financegeneral/masfinancialservices/MFS09',
 'Max Financial': '/india/stockpricequote/financeinvestments/maxfinancialservices/MI',
 'MCX India': '/india/stockpricequote/miscellaneous/multicommodityexchangeindia/MCE',
 'Metropolis': '/india/stockpricequote/hospitalsmedicalservices/metropolishealthcare/MH06',
 'Minda Corp': '/india/stockpricequote/autoancillaries/mindacorporation/MC23',
 'Minda Ind': '/india/stockpricequote/autoancillaries/mindaindustries/MI4',
 'Mindtree': '/india/stockpricequote/computerssoftware/mindtree/MT13',
 'Mishra Dhatu Ni': '/india/stockpricequote/miscellaneous/mishradhatunigamltd/MDN',
 'MMTC Ltd': '/india/stockpricequote/trading/mmtc/MMT',
 'MOIL': '/india/stockpricequote/miningminerals/moil/M18',
 'Motherson Sumi': '/india/stockpricequote/autoancillaries/mothersonsumisystems/MSS01',
 'Motilal Oswal': '/india/stockpricequote/financegeneral/motilaloswalfinancialservices/MOF01',
 'MphasiS': '/india/stockpricequote/computerssoftware/mphasis/MB02',
 'MRF': '/india/stockpricequote/tyres/mrf/MRF',
 'MRPL': '/india/stockpricequote/refineries/mangalorerefinerypetrochemicals/MRP',
 'Muthoot Finance': '/india/stockpricequote/financeinvestments/muthootfinance/MF10',
 'NALCO': '/india/stockpricequote/aluminium/nationalaluminiumcompany/NAC',
 'Narayana Hruda': '/india/stockpricequote/hospitalsmedicalservices/narayanahrudayalaya/NH',
 'Natco Pharma': '/india/stockpricequote/pharmaceuticals/natcopharma/NP07',
 'Nava Bharat Ven': '/india/stockpricequote/diversified/navabharatventures/NBV',
 'Navin Fluorine': '/india/stockpricequote/chemicals/navinfluorineinternational/NFI',
 'NBCC (India)': '/india/stockpricequote/infrastructuregeneral/nbccindia/NBC01',
 'NCC': '/india/stockpricequote/constructioncontractingcivil/ncc/NCC01',
 'NESCO': '/india/stockpricequote/diversified/nesco/NES',
 'Nestle': '/india/stockpricequote/foodprocessing/nestleindia/NI',
 'New India Assur': '/india/stockpricequote/miscellaneous/newindiaassurancecompany/NIA',
 'NFL': '/india/stockpricequote/fertilisers/nationalfertilizers/NF06',
 'NHPC': '/india/stockpricequote/powergenerationdistribution/nhpc/N07',
 'Nilkamal': '/india/stockpricequote/plastics/nilkamal/NP08',
 'Nippon': '/india/stockpricequote/miscellaneous/nipponlifeindiaassetmanagement/RNL',
 'NLC India': '/india/stockpricequote/powergenerationdistribution/nlcindia/NLC',
 'NMDC': '/india/stockpricequote/miningminerals/nmdc/NMD02',
 'NTPC': '/india/stockpricequote/powergenerationdistribution/ntpc/NTP',
 'Oberoi Realty': '/india/stockpricequote/constructioncontractingrealestate/oberoirealty/OR',
 'Oil India': '/india/stockpricequote/oildrillingandexploration/oilindia/OI13',
 'Omaxe': '/india/stockpricequote/constructioncontractingrealestate/omaxe/O02',
 'ONGC': '/india/stockpricequote/oildrillingandexploration/oilnaturalgascorporation/ONG',
 'Oracle Fin Serv': '/india/stockpricequote/computerssoftware/oraclefinancialservicessoftware/OFS01',
 'Orient Cement': '/india/stockpricequote/cementmajor/orientcement/OC10',
 'Orient Refract': '/india/stockpricequote/cementproductsbuildingmaterials/orientrefractories/OR01',
 'P and G': '/india/stockpricequote/personalcare/proctergamblehygienehealthcare/PGH',
 'Page Industries': '/india/stockpricequote/textilesreadymadeapparels/pageindustries/PI35',
 'Persistent': '/india/stockpricequote/computerssoftware/persistentsystems/PS15',
 'Petronet LNG': '/india/stockpricequote/oildrillingandexploration/petronetlng/PLN',
 'Pfizer': '/india/stockpricequote/pharmaceuticals/pfizer/P',
 'Phillips Carbon': '/india/stockpricequote/chemicals/phillipscarbonblack/PCB01',
 'Phoenix Mills': '/india/stockpricequote/constructioncontractingrealestate/phoenixmills/PM02',
 'PI Industries': '/india/stockpricequote/pesticidesagrochemicals/piindustries/PII',
 'Pidilite Ind': '/india/stockpricequote/chemicals/pidiliteindustries/PI11',
 'Piramal Enter': '/india/stockpricequote/pharmaceuticals/piramalenterprises/PH05',
 'PNB': '/india/stockpricequote/bankspublicsector/punjabnationalbank/PNB05',
 'PNB Housing Fin': '/india/stockpricequote/financehousing/pnbhousingfinance/PHF',
 'PNC Infratech': '/india/stockpricequote/constructioncontractingrealestate/pncinfratech/PI26',
 'Poly Medicure': '/india/stockpricequote/hospitalsmedicalservices/polymedicure/PM06',
 'Polycab': '/india/stockpricequote/cablespowerothers/polycabindia/PI44',
 'Power Finance': '/india/stockpricequote/financetermlendinginstitutions/powerfinancecorporation/PFC02',
 'Power Grid Corp': '/india/stockpricequote/powergenerationdistribution/powergridcorporationindia/PGC',
 'Praj Industries': '/india/stockpricequote/engineeringheavy/prajindustries/PI17',
 'Prestige Estate': '/india/stockpricequote/constructioncontractingrealestate/prestigeestatesprojects/PEP02',
 'Prism Cement': '/india/stockpricequote/cementmajor/prismjohnson/PC',
 'Procter&Gamble': '/india/stockpricequote/pharmaceuticals/proctergamblehealth/M12',
 'PTC India': '/india/stockpricequote/trading/ptcindia/PTC02',
 'PVR': '/india/stockpricequote/mediaentertainment/pvr/PVR',
 'Quess Corp': '/india/stockpricequote/engineering/quesscorp/QC',
 'Radico Khaitan': '/india/stockpricequote/breweriesdistilleries/radicokhaitan/RK01',
 'Rail Vikas': '/india/stockpricequote/miscellaneous/railvikasnigam/RVN',
 'Rain Industries': '/india/stockpricequote/cementmajor/rainindustries/RC12',
 'Rajesh Exports': '/india/stockpricequote/diamondcuttingjewellerypreciousmetals/rajeshexports/RE07',
 'Rallis India': '/india/stockpricequote/pesticidesagrochemicals/rallisindia/RI03',
 'Ramco Cements': '/india/stockpricequote/cementmajor/theramcocements/MC',
 'Rashtriya Chem': '/india/stockpricequote/fertilisers/rashtriyachemicalsfertilisers/RCF01',
 'Ratnamani Metal': '/india/stockpricequote/steeltubespipes/ratnamanimetalstubes/RMT',
 'Raymond': '/india/stockpricequote/textileswoollenworsted/raymond/R',
 'RBL Bank': '/india/stockpricequote/banksprivatesector/rblbank/RB03',
 'REC': '/india/stockpricequote/financetermlendinginstitutions/rec/REC02',
 'Redington': '/india/stockpricequote/computershardware/redingtonindia/RI37',
 'Relaxo Footwear': '/india/stockpricequote/leatherproducts/relaxofootwears/RF07',
 'Reliance': '/india/stockpricequote/refineries/relianceindustries/RI',
 'Repco Home': '/india/stockpricequote/financehousing/repcohomefinance/RHF',
 'RITES': '/india/stockpricequote/diversified/rites/R02',
 'Sadbhav Engg': '/india/stockpricequote/infrastructuregeneral/sadbhavengineering/SE19',
 'SAIL': '/india/stockpricequote/steellarge/steelauthorityindia/SAI',
 'Sanofi India': '/india/stockpricequote/pharmaceuticals/sanofiindia/AP26',
 'SBI': '/india/stockpricequote/bankspublicsector/statebankindia/SBI',
 'SBI Life Insura': '/india/stockpricequote/diversified/sbilifeinsurancecompany/SLI03',
 'Schaeffler Ind': '/india/stockpricequote/bearings/schaefflerindia/FAG',
 'Schneider Infra': '/india/stockpricequote/powergenerationdistribution/schneiderelectricinfrastructure/SEI04',
 'Sequent Scienti': '/india/stockpricequote/pharmaceuticals/sequentscientific/PID01',
 'Sheela Foam': '/india/stockpricequote/miscellaneous/sheelafoam/SF14',
 'Shipping Corp': '/india/stockpricequote/shipping/shippingcorporationindia/SCI',
 'Shoppers Stop': '/india/stockpricequote/retail/shoppersstop/SS51',
 'Shree Cements': '/india/stockpricequote/cementmajor/shreecements/SC12',
 'Shree Renuka': '/india/stockpricequote/sugar/shreerenukasugars/SRS03',
 'Shriram City': '/india/stockpricequote/financeleasinghirepurchase/shriramcityunionfinance/SCU',
 'Shriram Trans': '/india/stockpricequote/financeleasinghirepurchase/shriramtransportfinancecorporation/STF',
 'Siemens': '/india/stockpricequote/infrastructuregeneral/siemens/S',
 'SIS': '/india/stockpricequote/miscellaneous/sis/SIS08',
 'SJVN': '/india/stockpricequote/powergenerationdistribution/sjvn/S11',
 'SKF India': '/india/stockpricequote/bearings/skfindia/SKF01',
 'Sobha': '/india/stockpricequote/constructioncontractingrealestate/sobha/SD6',
 'Solar Ind': '/india/stockpricequote/chemicals/solarindustriesindia/SII04',
 'Sonata': '/india/stockpricequote/computerssoftwaremediumsmall/sonatasoftware/SS42',
 'South Ind Bk': '/india/stockpricequote/banksprivatesector/southindianbank/SIB',
 'SpiceJet': '/india/stockpricequote/transportlogistics/spicejet/SJ01',
 'SRF': '/india/stockpricequote/diversified/srf/SRF',
 'Star Cement': '/india/stockpricequote/cementmajor/starcement/SFC02',
 'Sterlite Techno': '/india/stockpricequote/cablestelephone/sterlitetechnologies/ST20',
 'Strides Pharma ': '/india/stockpricequote/pharmaceuticals/stridespharmascience/SA10',
 'Sudarshan Chem': '/india/stockpricequote/dyespigments/sudarshanchemicalindustries/SCI08',
 'SUMITOMO': '/india/stockpricequote/pesticidesagrochemicals/sumitomochemicalindialimite/SUMIC54292',
 'Sun Pharma': '/india/stockpricequote/pharmaceuticals/sunpharmaceuticalindustries/SPI',
 'Sun Pharma Adv': '/india/stockpricequote/pharmaceuticals/sunpharmaadvancedresearchcompany/SPA',
 'Sun TV Network': '/india/stockpricequote/mediaentertainment/suntvnetwork/STN01',
 'Sundaram Fin': '/india/stockpricequote/financeleasinghirepurchase/sundaramfinance/SF20',
 'Sundram': '/india/stockpricequote/fasteners/sundramfasteners/SF23',
 'Sunteck Realty': '/india/stockpricequote/constructioncontractingrealestate/sunteckrealty/SR05',
 'Suprajit Eng': '/india/stockpricequote/autoancillaries/suprajitengineering/SE15',
 'Supreme Ind': '/india/stockpricequote/plastics/supremeindustries/SI48',
 'Suzlon Energy': '/india/stockpricequote/powergenerationdistribution/suzlonenergy/SE17',
 'Swan Energy': '/india/stockpricequote/trading/swanenergy/SM09',
 'Symphony': '/india/stockpricequote/consumergoodswhitegoods/symphony/SCS04',
 'Syngene Intl': '/india/stockpricequote/miscellaneous/syngeneinternational/SI10',
 'Tasty Bite': '/india/stockpricequote/foodprocessing/tastybiteeatables/TBE',
 'Tata Comm': '/india/stockpricequote/telecommunicationsservice/tatacommunications/TC17',
 'TATA Cons. Prod': '/india/stockpricequote/plantationsteacoffee/tataconsumerproducts/TT',
 'Tata Elxsi': '/india/stockpricequote/computerssoftware/tataelxsi/TE',
 'Tata Inv Corp': '/india/stockpricequote/financeinvestments/tatainvestmentcorporation/TIC',
 'Tata Motors': '/india/stockpricequote/autolcvshcvs/tatamotors/TM03',
 'Tata Power': '/india/stockpricequote/powergenerationdistribution/tatapowercompany/TPC',
 'Tata Steel': '/india/stockpricequote/steellarge/tatasteel/TIS',
 'Tata Steel BSL ': '/india/stockpricequote/steelcrhrstrips/tatasteelbsllimited/BS14',
 'TCNS Clothing C': '/india/stockpricequote/textilesgeneral/tcnsclothingco/TCC',
 'TCS': '/india/stockpricequote/computerssoftware/tataconsultancyservices/TCS',
 'TeamLease Ser.': '/india/stockpricequote/miscellaneous/teamleaseservices/TS13',
 'Tech Mahindra': '/india/stockpricequote/computerssoftware/techmahindra/TM4',
 'Thermax': '/india/stockpricequote/infrastructuregeneral/thermax/T',
 'Thyrocare Techn': '/india/stockpricequote/hospitalsmedicalservices/thyrocaretechnologies/TT16',
 'Time Techno': '/india/stockpricequote/packaging/timetechnoplast/TT03',
 'Timken': '/india/stockpricequote/bearings/timkenindia/TI23',
 'Titan Company': '/india/stockpricequote/miscellaneous/titancompany/TI01',
 'TML-D': '/india/stockpricequote/miscellaneous/tatamotorsltddvr/TATAM57000',
 'Torrent Pharma': '/india/stockpricequote/pharmaceuticals/torrentpharmaceuticals/TP06',
 'Torrent Power': '/india/stockpricequote/powergenerationdistribution/torrentpower/TP14',
 'Trent': '/india/stockpricequote/retail/trent/T04',
 'Trident': '/india/stockpricequote/textilesspinningcottonblended/trident/AI01',
 'TTK Prestige': '/india/stockpricequote/domesticappliances/ttkprestige/TTK02',
 'TV TodayNetwork': '/india/stockpricequote/mediaentertainment/tvtodaynetwork/TVT',
 'TV18 Broadcast': '/india/stockpricequote/mediaentertainment/tv18broadcast/IBN',
 'TVS Motor': '/india/stockpricequote/auto23wheelers/tvsmotorcompany/TVS',
 'UCO Bank': '/india/stockpricequote/bankspublicsector/ucobank/UCO',
 'Uflex': '/india/stockpricequote/packaging/uflex/U01',
 'Ujjivan Financi': '/india/stockpricequote/financegeneral/ujjivanfinancialservices/UFS01',
 'UltraTechCement': '/india/stockpricequote/cementmajor/ultratechcement/UTC01',
 'Union Bank': '/india/stockpricequote/bankspublicsector/unionbankindia/UBI01',
 'United Brewerie': '/india/stockpricequote/breweriesdistilleries/unitedbreweries/UB02',
 'United Spirits': '/india/stockpricequote/breweriesdistilleries/unitedspirits/US',
 'UPL': '/india/stockpricequote/chemicals/upl/UP04',
 'V-Guard Ind': '/india/stockpricequote/electricequipment/vguardindustries/VI02',
 'V-Mart Retail': '/india/stockpricequote/retail/vmartretail/VR03',
 'Vaibhav Global': '/india/stockpricequote/retail/vaibhavglobal/VG02',
 'Vakrangee': '/india/stockpricequote/computerssoftwaremediumsmall/vakrangee/VS',
 'Vardhman Text': '/india/stockpricequote/textilesspinningcottonblended/vardhmantextiles/VT10',
 'Varroc Engineer': '/india/stockpricequote/engineeringheavy/varrocengineering/VE08',
 'Varun Beverages': '/india/stockpricequote/foodprocessing/varunbeverages/VB05',
 'Vedanta': '/india/stockpricequote/miningminerals/vedanta/SG',
 'Venkys': '/india/stockpricequote/miscellaneous/venkys/V03',
 'Vesuvius India': '/india/stockpricequote/cementproductsbuildingmaterials/vesuviusindia/VI06',
 'Vinati Organics': '/india/stockpricequote/chemicals/vinatiorganics/VO01',
 'VIP Industries': '/india/stockpricequote/householdpersonalproducts/vipindustries/VIP',
 'Vodafone Idea': '/india/stockpricequote/telecommunicationsservice/vodafoneidealimited/IC8',
 'Voltas': '/india/stockpricequote/diversified/voltas/V',
 'VRL Logistics': '/india/stockpricequote/transportlogistics/vrllogistics/VL03',
 'VST': '/india/stockpricequote/cigarettes/vstindustries/VST',
 'WABCO India': '/india/stockpricequote/autoancillaries/wabcoindia/WAB',
 'Welspun Corp': '/india/stockpricequote/steeltubespipes/welspuncorp/WGS',
 'Welspun India': '/india/stockpricequote/textilesweaving/welspunindia/WI03',
 'Westlife Dev': '/india/stockpricequote/hotels/westlifedevelopment/DIC',
 'Whirlpool': '/india/stockpricequote/consumergoodswhitegoods/whirlpoolindia/WI',
 'Wipro': '/india/stockpricequote/computerssoftware/wipro/W',
 'Wockhardt': '/india/stockpricequote/pharmaceuticals/wockhardt/W05',
 'Zee Entertain': '/india/stockpricequote/mediaentertainment/zeeentertainmententerprises/ZEE',
 'Zensar Tech': '/india/stockpricequote/computerssoftware/zensartechnologies/ZT02',
 'Zydus Wellness': '/india/stockpricequote/vanaspatioils/zyduswellness/ZW01'}