codes = {'3M India': ['3MINDIA', '523395'],
 'Aarti Ind': ['AARTIIND'],
 'AAVAS Financier': ['AAVAS', '541988'],
 'AB Capital': ['ABCAPITAL'],
 'ABB India': ['ABB', '500002'],
 'Abbott India': ['ABBOTINDIA', '500488'],
 'ACC': ['ACC', '500410'],
 'Adani Ports': ['ADANIPORTS'],
 'Adani Power': ['ADANIPOWER', '533096'],
 'Adani Total Gas': ['ATGL', '542066'],
 'Adani Trans': ['ADANITRANS'],
 'Aditya Birla F': ['ABFRL'],
 'Advanced Enzyme': ['ADVENZYMES'],
 'Aegis Logistics': ['AEGISCHEM'],
 'AFL': ['ARVINDFASN'],
 'AIA Engineering': ['AIAENG'],
 'Ajanta Pharma': ['AJANTPHARM'],
 'Akzo Nobel': ['AKZOINDIA'],
 'Alembic Pharma': ['APLLTD'],
 'Alkem Lab': ['ALKEM'],
 'Alkyl Amines': ['ALKYLAMINE'],
 'Allcargo': ['ALLCARGO'],
 'Amara Raja Batt': ['AMARAJABAT'],
 'Amber Enterpris': ['AMBER'],
 'Ambuja Cements': ['AMBUJACEM'],
 'APL Apollo': ['APLAPOLLO'],
 'Apollo Hospital': ['APOLLOHOSP'],
 'Apollo Tyres': ['APOLLOTYRE', '500877'],
 'Asahi India': ['ASAHIINDIA'],
 'Ashok Leyland': ['ASHOKLEY', '500477'],
 'Ashoka Buildcon': ['ASHOKA', '533271'],
 'Asian Paints': ['ASIANPAINT', '500820'],
 'Aster DM Health': ['ASTERDM'],
 'Astral Poly Tec': ['ASTRAL'],
 'AstraZeneca': ['ASTRAZEN'],
 'Atul': ['ATUL', '500027'],
 'AU Small Financ': ['AUBANK'],
 'Aurobindo Pharm': ['AUROPHARMA'],
 'Avanti Feeds': ['AVANTIFEED'],
 'Avenue Supermar': ['DMART'],
 'Axis Bank': ['AXISBANK', '532215'],
 'Bajaj Auto': ['BAJAJ-AUTO', '532977'],
 'Bajaj Consumer ': ['BAJAJCON'],
 'Bajaj Electric': ['BAJAJELEC'],
 'Bajaj Finance': ['BAJFINANCE', '500034'],
 'Bajaj Finserv': ['BAJAJFINSV'],
 'Bajaj Holdings': ['BAJAJHLDNG'],
 'Balkrishna Ind': ['BALKRISIND'],
 'Balmer Lawrie': ['BALMLAWRIE'],
 'Balrampur Chini': ['BALRAMCHIN'],
 'Bandhan Bank': ['BANDHANBNK'],
 'Bank of Baroda': ['BANKBARODA', '532134'],
 'Bank of India': ['BANKINDIA', '532149'],
 'Bank of Mah': ['MAHABANK'],
 'BASF': ['BASF', '500042'],
 'Bata India': ['BATAINDIA', '500043'],
 'Bayer CropScien': ['BAYERCROP'],
 'BEML': ['BEML', '500048'],
 'Berger Paints': ['BERGEPAINT'],
 'Bharat Dynamics': ['BDL'],
 'Bharat Elec': ['BEL', '500049'],
 'Bharat Forge': ['BHARATFORG', '500493'],
 'Bharat Rasayan': ['BHARATRAS'],
 'Bharti Airtel': ['BHARTIARTL'],
 'BHEL': ['BHEL'],
 'Biocon': ['BIOCON', '532523'],
 'Birla Corp': ['BIRLACORPN'],
 'Birlasoft': ['BSOFT', '532400'],
 'Bliss GVS': ['BLISSGVS'],
 'Blue Dart': ['BLUEDART'],
 'Blue Star': ['BLUESTARCO', '500067'],
 'Bombay Burmah': ['BBTC'],
 'Bombay Dyeing': ['BOMDYEING'],
 'Bosch': ['BOSCHLTD', '500530'],
 'BPCL': ['BPCL'],
 'Brigade Ent': ['BRIGADE'],
 'Britannia': ['BRITANNIA'],
 'BSE Limited': ['N/A', 'N/A'],
 'Cadila Health': ['CADILAHC'],
 'Can Fin Homes': ['CANFINHOME', '511196'],
 'Canara Bank': ['CANBK', '532483'],
 'Caplin Labs': ['CAPLIPOINT'],
 'Capri Global': ['CGCL'],
 'Carborundum': ['CARBORUNIV'],
 'CARE Ratings': ['CARERATING', '534804'],
 'Castrol': ['CASTROLIND'],
 'CCL Products': ['CCL', '519600'],
 'CDSL': [],
 'Ceat': ['CEATLTD', '500878'],
 'Central Bank': ['CENTRALBK'],
 'Century': ['CENTURYTEX'],
 'CenturyPlyboard': ['CENTURYPLY'],
 'Cera Sanitary': ['CERA', '532443'],
 'CESC': ['CESC', '500084'],
 'CG Consumer': ['CROMPTON'],
 'Chambal Fert': ['CHAMBLFERT'],
 'Chennai Petro': ['CHENNPETRO'],
 'Cholamandalam': ['CHOLAHLDNG'],
 'Cholamandalam': ['CHOLAFIN'],
 'Cipla': ['CIPLA', '500087'],
 'City Union Bank': ['CUB', '532210'],
 'Coal India': ['COALINDIA', '533278'],
 'Cochin Shipyard': ['COCHINSHIP'],
 'COFORGE LTD.': ['COFORGE'],
 'Colgate': ['COLPAL'],
 'Container Corp': ['CONCOR'],
 'Coromandel Int': ['COROMANDEL'],
 'CreditAccess Gr': ['CREDITACC'],
 'CRISIL': ['CRISIL', '500092'],
 'Cummins': ['CUMMINSIND'],
 'Cyient': ['CYIENT', '532175'],
 'Dabur India': ['DABUR', '500096'],
 'Dalmia Bharat': ['DALBHARAT', '542216'],
 'DB Corp': ['DBCORP', '533151'],
 'DCB Bank': ['DCBBANK', '532772'],
 'DCM Shriram': ['DCMSHRIRAM'],
 'Deepak Nitrite': ['DEEPAKNTR', '506401'],
 'Delta Corp': ['DELTACORP', '532848'],
 'Dhani Services': ['DHANI', '532960'],
 'Dhanuka Agritec': ['DHANUKA'],
 'Dilip Buildcon': ['DBL', '540047'],
 'Dish TV': ['DISHTV', '532839'],
 'Dishman Carboge': ['DCAL'],
 'Divis Labs': ['DIVISLAB'],
 'Dixon Technolog': ['DIXON'],
 'DLF': ['DLF', '532868'],
 'Dr Lal PathLab': ['LALPATHLAB'],
 'Dr Reddys Labs': ['DRREDDY'],
 'eClerx Services': ['ECLERX', '532927'],
 'Edelweiss': ['EDELWEISS'],
 'Eicher Motors': ['EICHERMOT', '505200'],
 'EID Parry': ['EIDPARRY', '500125'],
 'EIH': ['EIHOTEL', '500840'],
 'Elgi Equipments': ['ELGIEQUIP'],
 'Emami': ['EMAMILTD', '531162'],
 'Endurance Techn': ['ENDURANCE'],
 'EngineersInd': ['ENGINERSIN'],
 'EPL': ['EPL', '500135'],
 'Equitas Holding': ['EQUITAS'],
 'Esab India': ['ESABINDIA', '500133'],
 'Escorts': ['ESCORTS', '500495'],
 'Exide Ind': ['EXIDEIND', '500086'],
 'FDC': ['FDC', '531599'],
 'Federal Bank': ['FEDERALBNK', '500469'],
 'Fine Organics': ['FINEORG'],
 'Finolex Cables': ['FINCABLES'],
 'Finolex Ind': ['FINPIPE', '500940'],
 'Firstsource Sol': ['FSL'],
 'Fortis Health': ['FORTIS', '532843'],
 'Future Consumer': ['FCONSUMER'],
 'Future Retail': ['FRETAIL', '540064'],
 'GAIL': ['GAIL', '532155'],
 'Galaxy Surfacta': ['GALAXYSURF'],
 'Garden Reach Sh': ['GRSE'],
 'Garware Technic': ['GARFIBRES'],
 'GE Power India': ['GEPIL', '532309'],
 'GE Shipping': ['GESHIP'],
 'GE T&D India': ['GET&D', '522275'],
 'General Insuran': ['GICRE'],
 'Gillette India': ['GILLETTE', '507815'],
 'GlaxoSmithKline': ['GLAXO'],
 'Glenmark': ['GLENMARK'],
 'GMM Pfaudler': ['GMMPFAUDLR'],
 'GMR Infra': ['GMRINFRA'],
 'GNFC': ['GNFC'],
 'Godfrey Phillip': ['GODFRYPHLP'],
 'Godrej Agrovet': ['GODREJAGRO'],
 'Godrej Consumer': ['GODREJCP'],
 'Godrej Ind': ['GODREJIND'],
 'Godrej Prop': ['GODREJPROP'],
 'Granules India': ['GRANULES'],
 'Graphite India': ['GRAPHITE'],
 'Grasim': ['GRASIM'],
 'Greaves Cotton': ['GREAVESCOT', '501455'],
 'Grindwell Norto': ['GRINDWELL', '506076'],
 'GSFC': ['GSFC'],
 'Guj Alkali': ['GUJALKALI'],
 'Guj Heavy Chem': ['GHCL'],
 'Guj Mineral': ['GMDCLTD'],
 'Guj State Petro': ['GSPL'],
 'Gujarat Fluoro': ['Y'],
 'Gujarat Gas': ['GUJGASLTD', '539336'],
 'Gujarat Pipavav': ['GPPL'],
 'Gulf Oil Lubric': ['GULFOILLUB'],
 'Hathway Cable': ['HATHWAY'],
 'Hatsun Agro': ['HATSUN'],
 'Havells India': ['HAVELLS', '517354'],
 'HCL Tech': ['HCLTECH'],
 'HDFC': ['HDFC'],
 'HDFC AMC': ['HDFCAMC'],
 'HDFC Bank': ['HDFCBANK', '500180'],
 'HDFC Life': ['HDFCLIFE'],
 'HEG': ['HEG', '509631'],
 'Heidelberg Cem': ['HEIDELBERG'],
 'Heritage Foods': ['HERITGFOOD'],
 'Hero Motocorp': ['HEROMOTOCO', '500182'],
 'Hexaware Tech': ['HEXAWARE'],
 'HFCL': ['HFCL', '500183'],
 'Himadri Special': ['HSCL'],
 'Himatsingka Sei': ['HIMATSEIDE'],
 'Hind Copper': ['HINDCOPPER'],
 'Hind Zinc': ['HINDZINC', '500188'],
 'Hindalco': ['HINDALCO'],
 'Hindustan Aeron': ['HAL'],
 'Honeywell Autom': ['HONAUT'],
 'HPCL': ['HINDPETRO'],
 'HUDCO': ['HUDCO'],
 'HUL': ['HINDUNILVR'],
 'ICICI Bank': ['ICICIBANK', '532174'],
 'ICICI Lombard ': ['ICICIGI'],
 'ICICI Prudentia': ['Y'],
 'ICICI Securitie': ['ISEC'],
 'ICRA': ['ICRA', '532835'],
 'IDBI Bank': ['IDBI', '500116'],
 'IDFC': ['IDFC', '532659'],
 'IDFC First Bank': ['IDFCFIRSTB'],
 'IEX': ['IEX'],
 'IFB Industries': ['IFBIND'],
 'IFCI': ['IFCI', '500106'],
 'IGL': ['IGL', '532514'],
 'IIFL Finance': ['IIFL', '532636'],
 'India Cements': ['INDIACEM', '530005'],
 'India Tourism D': ['ITDC'],
 'Indiabulls Hsg': ['IBULHSGFIN'],
 'Indiabulls Real': ['IBREALEST'],
 'Indiamart Inter': ['INDIAMART'],
 'Indian Bank': ['INDIANB', '532814'],
 'Indian Hotels': ['INDHOTEL'],
 'Indoco Remedies': ['INDOCO', '532612'],
 'Indostar Capita': ['INDOSTAR'],
 'INDUS TOWERS': ['INDUSTOWER'],
 'IndusInd Bank': ['INDUSINDBK', '532187'],
 'Infibeam Avenue': ['INFIBEAM'],
 'Info Edge': ['NAUKRI'],
 'Infosys': ['INFY', '500209'],
 'Ingersoll Rand': ['INGERRAND'],
 'INOX Leisure': ['INOXLEISUR'],
 'Intellect Desig': ['INTELLECT'],
 'Interglobe Avi': ['INDIGO'],
 'IOB': ['IOB', '532388'],
 'IOC': ['IOC'],
 'Ipca Labs': ['IPCALAB', '524494'],
 'IRB Infra': ['IRB'],
 'Ircon Internati': ['IRCON'],
 'IRCTC': ['IRCTC'],
 'ITC': ['ITC', '500875'],
 'ITI': ['ITI', '523610'],
 'IWML': ['IIFLWAM'],
 'J. K. Cement': ['JKCEMENT', '532644'],
 'JagranPrakashan': ['JAGRAN'],
 'Jai Corp': ['JAICORPLTD', '512237'],
 'Jamna Auto': ['JAMNAAUTO'],
 'JB Chemicals': ['JBCHEPHARM'],
 'Jindal (Hisar)': ['JSLHISAR'],
 'Jindal Saw': ['JINDALSAW', '500378'],
 'Jindal Stainles': ['JSL', '532508'],
 'Jindal Steel': ['JINDALSTEL'],
 'JK Bank': ['J&KBANK'],
 'JK Lakshmi Cem': ['JKLAKSHMI'],
 'JK Paper': ['JKPAPER', '532162'],
 'JK Tyre & Ind': ['JKTYRE'],
 'JM Financial': ['JMFINANCIL', '523405'],
 'Johnson Control': ['Y'],
 'JSW Energy': ['JSWENERGY', '533148'],
 'JSW Steel': ['JSWSTEEL', '500228'],
 'Jubilant Food': ['JUBLFOOD'],
 'Jubilant Pharmo': ['JUBLPHARMA'],
 'Just Dial': ['JUSTDIAL', '535648'],
 'Jyothy Labs': ['JYOTHYLAB', '532926'],
 'Kajaria Ceramic': ['KAJARIACER'],
 'Kalpataru Power': ['KALPATPOWR'],
 'Kansai Nerolac': ['KANSAINER'],
 'Karnataka Bank': ['KTKBANK', '532652'],
 'Karur Vysya': ['KARURVYSYA'],
 'Kaveri Seed': ['KSCL'],
 'KEC Intl': ['KEC'],
 'KEI Industries': ['KEI', '517569'],
 'KNR Construct': ['KNRCON'],
 'Kolte-Patil': ['KOLTEPATIL'],
 'Kotak Mahindra': ['KOTAKBANK'],
 'KPIT Tech': ['KPITTECH'],
 'KPR Mill': ['KPRMILL', '532889'],
 'KRBL': ['KRBL', '530813'],
 'KSB Pumps': ['KSB', '500249'],
 'L&T Finance': ['L&TFH', '533519'],
 'L&T Infotech': ['LTI'],
 'L&T Technology': ['LTTS'],
 'La Opala RG': ['LAOPALA', '526947'],
 'Lakshmi Machine': ['LAXMIMACH'],
 'Larsen': ['LT', '500510'],
 'Laurus Labs': ['LAURUSLABS', '540222'],
 'Lemon Tree Hote': ['LEMONTREE'],
 'LIC Housing Fin': ['LICHSGFIN'],
 'Linde India': ['LINDEINDIA', '523457'],
 'Lupin': ['LUPIN', '500257'],
 'Lux Industries': ['LUXIND', '539542'],
 'M&M': ['M&M', '500520'],
 'Mah Scooters': ['MAHSCOOTER'],
 'Mah Seamless': ['MAHSEAMLES'],
 'Mahanagar Gas': ['MGL', '539957'],
 'Mahindra CIE': ['MAHINDCIE'],
 'Mahindra Holida': ['MHRIL'],
 'Mahindra Logist': ['MAHLOG'],
 'Manappuram Fin': ['MANAPPURAM'],
 'Marico': ['MARICO', '531642'],
 'Maruti Suzuki': ['MARUTI'],
 'MAS Financial S': ['MASFIN'],
 'Max Financial': ['MFSL', '500271'],
 'MCX India': ['MCX'],
 'Metropolis': ['METROPOLIS'],
 'Minda Corp': ['MINDACORP'],
 'Minda Ind': ['MINDAIND'],
 'Mindtree': ['MINDTREE', '532819'],
 'Mishra Dhatu Ni': ['MIDHANI'],
 'MMTC Ltd': ['MMTC', '513377'],
 'MOIL': ['MOIL', '533286'],
 'Motherson Sumi': ['MOTHERSUMI'],
 'Motilal Oswal': ['MOTILALOFS'],
 'MphasiS': ['MPHASIS', '526299'],
 'MRF': ['MRF', '500290'],
 'MRPL': ['MRPL'],
 'Muthoot Finance': ['MUTHOOTFIN'],
 'NALCO': ['NATIONALUM'],
 'Narayana Hruda': ['NH', '539551'],
 'Natco Pharma': ['NATCOPHARM'],
 'Nava Bharat Ven': ['NBVENTURES'],
 'Navin Fluorine': ['NAVINFLUOR'],
 'NBCC (India)': ['NBCC', '534309'],
 'NCC': ['NCC', '500294'],
 'NESCO': ['NESCO', '505355'],
 'Nestle': ['NESTLEIND', '500790'],
 'New India Assur': ['NIACL'],
 'NFL': ['NFL'],
 'NHPC': ['NHPC', '533098'],
 'Nilkamal': ['NILKAMAL', '523385'],
 'Nippon': ['NAM-INDIA'],
 'NLC India': ['NLCINDIA', '513683'],
 'NMDC': ['NMDC', '526371'],
 'NTPC': [],
 'Oberoi Realty': ['OBEROIRLTY', '533273'],
 'Oil India': ['OIL', '533106'],
 'Omaxe': ['OMAXE', '532880'],
 'ONGC': ['ONGC'],
 'Oracle Fin Serv': ['OFSS'],
 'Orient Cement': ['ORIENTCEM'],
 'Orient Refract': ['ORIENTREF'],
 'P and G': ['PGHH'],
 'Page Industries': ['PAGEIND'],
 'Persistent': ['PERSISTENT'],
 'Petronet LNG': ['PETRONET', '532522'],
 'Pfizer': ['PFIZER', '500680'],
 'Phillips Carbon': ['PHILIPCARB'],
 'Phoenix Mills': ['PHOENIXLTD'],
 'PI Industries': ['PIIND', '523642'],
 'Pidilite Ind': ['PIDILITIND'],
 'Piramal Enter': ['PEL'],
 'PNB': ['PNB'],
 'PNB Housing Fin': ['PNBHOUSING'],
 'PNC Infratech': ['PNCINFRA', '539150'],
 'Poly Medicure': ['POLYMED', '531768'],
 'Polycab': ['POLYCAB', '542652'],
 'Power Finance': ['PFC'],
 'Power Grid Corp': ['POWERGRID'],
 'Praj Industries': ['PRAJIND'],
 'Prestige Estate': ['PRESTIGE'],
 'Prism Cement': ['PRSMJOHNSN', '500338'],
 'Procter&Gamble': ['PGHL'],
 'PTC India': ['PTC', '532524'],
 'PVR': ['PVR', '532689'],
 'Quess Corp': ['QUESS', '539978'],
 'Radico Khaitan': ['RADICO', '532497'],
 'Rail Vikas': ['RVNL', '542649'],
 'Rain Industries': ['RAIN', '500339'],
 'Rajesh Exports': ['RAJESHEXPO'],
 'Rallis India': ['RALLIS', '500355'],
 'Ramco Cements': ['RAMCOCEM', '500260'],
 'Rashtriya Chem': ['RCF'],
 'Ratnamani Metal': ['RATNAMANI'],
 'Raymond': ['RAYMOND', '500330'],
 'RBL Bank': ['RBLBANK', '540065'],
 'REC': ['RECLTD', '532955'],
 'Redington': ['REDINGTON'],
 'Relaxo Footwear': ['RELAXO'],
 'Reliance': ['RELIANCE'],
 'Repco Home': ['REPCOHOME'],
 'RITES': ['RITES', '541556'],
 'Sadbhav Engg': ['SADBHAV'],
 'SAIL': ['SAIL'],
 'Sanofi India': ['SANOFI', '500674'],
 'SBI': ['SBIN', '500112'],
 'SBI Life Insura': ['SBILIFE'],
 'Schaeffler Ind': ['SCHAEFFLER'],
 'Schneider Infra': ['SCHNEIDER'],
 'Sequent Scienti': ['SEQUENT'],
 'Sheela Foam': ['SFL', '540203'],
 'Shipping Corp': ['SCI'],
 'Shoppers Stop': ['SHOPERSTOP'],
 'Shree Cements': ['SHREECEM', '500387'],
 'Shree Renuka': ['RENUKA'],
 'Shriram City': ['SHRIRAMCIT'],
 'Shriram Trans': ['SRTRANSFIN'],
 'Siemens': ['SIEMENS', '500550'],
 'SIS': ['SIS', '540673'],
 'SJVN': ['SJVN', '533206'],
 'SKF India': ['SKFINDIA', '500472'],
 'Sobha': ['SOBHA', '532784'],
 'Solar Ind': ['SOLARINDS'],
 'Sonata': ['SONATSOFTW'],
 'South Ind Bk': ['SOUTHBANK'],
 'SpiceJet': ['SPICEJET', '500285'],
 'SRF': ['SRF', '503806'],
 'Star Cement': ['STARCEMENT'],
 'Sterlite Techno': ['STLTECH'],
 'Strides Pharma ': ['STAR'],
 'Sudarshan Chem': ['SUDARSCHEM'],
 'SUMITOMO': ['Y'],
 'Sun Pharma': ['SUNPHARMA'],
 'Sun Pharma Adv': ['SPARC'],
 'Sun TV Network': ['SUNTV', '532733'],
 'Sundaram Fin': ['SUNDARMFIN'],
 'Sundram': ['SUNDRMFAST'],
 'Sunteck Realty': ['SUNTECK', '512179'],
 'Suprajit Eng': ['SUPRAJIT'],
 'Supreme Ind': ['SUPREMEIND'],
 'Suzlon Energy': ['SUZLON', '532667'],
 'Swan Energy': ['SWANENERGY', '503310'],
 'Symphony': ['SYMPHONY', '517385'],
 'Syngene Intl': ['SYNGENE'],
 'Tasty Bite': ['TASTYBITE'],
 'Tata Comm': ['TATACOMM'],
 'TATA Cons. Prod': ['TATACONSUM'],
 'Tata Elxsi': ['TATAELXSI', '500408'],
 'Tata Inv Corp': ['TATAINVEST'],
 'Tata Motors': ['TATAMOTORS', '500570'],
 'Tata Power': ['TATAPOWER'],
 'Tata Steel': ['TATASTEEL', '500470'],
 'Tata Steel BSL ': ['TATASTLBSL'],
 'TCNS Clothing C': ['TCNSBRANDS'],
 'TCS': ['TCS'],
 'TeamLease Ser.': ['TEAMLEASE'],
 'Tech Mahindra': ['TECHM', '532755'],
 'Thermax': ['THERMAX', '500411'],
 'Thyrocare Techn': ['THYROCARE'],
 'Time Techno': ['TIMETECHNO'],
 'Timken': ['TIMKEN', '522113'],
 'Titan Company': ['TITAN', '500114'],
 'TML-D': ['TATAMTRDVR'],
 'Torrent Pharma': ['TORNTPHARM'],
 'Torrent Power': ['TORNTPOWER'],
 'Trent': ['TRENT', '500251'],
 'Trident': ['TRIDENT', '521064'],
 'TTK Prestige': ['TTKPRESTIG'],
 'TV TodayNetwork': ['TVTODAY', '532515'],
 'TV18 Broadcast': ['TV18BRDCST'],
 'TVS Motor': ['TVSMOTOR'],
 'UCO Bank': ['UCOBANK', '532505'],
 'Uflex': ['UFLEX', '500148'],
 'Ujjivan Financi': ['UJJIVAN'],
 'UltraTechCement': ['ULTRACEMCO'],
 'Union Bank': ['UNIONBANK'],
 'United Brewerie': ['UBL', '532478'],
 'United Spirits': ['MCDOWELL-N'],
 'UPL': ['UPL', '512070'],
 'V-Guard Ind': ['VGUARD'],
 'V-Mart Retail': ['VMART', '534976'],
 'Vaibhav Global': ['VAIBHAVGBL'],
 'Vakrangee': ['VAKRANGEE', '511431'],
 'Vardhman Text': ['VTL', '502986'],
 'Varroc Engineer': ['VARROC'],
 'Varun Beverages': ['VBL', '540180'],
 'Vedanta': ['VEDL', '500295'],
 'Venkys': ['VENKEYS', '523261'],
 'Vesuvius India': ['VESUVIUS'],
 'Vinati Organics': ['VINATIORGA'],
 'VIP Industries': ['VIPIND', '507880'],
 'Vodafone Idea': ['IDEA'],
 'Voltas': ['VOLTAS', '500575'],
 'VRL Logistics': ['VRLLOG', '539118'],
 'VST': ['VSTIND', '509966'],
 'WABCO India': ['WABCOINDIA', '533023'],
 'Welspun Corp': ['WELCORP', '532144'],
 'Welspun India': ['WELSPUNIND'],
 'Westlife Dev': ['WESTLIFE'],
 'Whirlpool': ['WHIRLPOOL', '500238'],
 'Wipro': ['WIPRO', '507685'],
 'Wockhardt': ['WOCKPHARMA', '532300'],
 'Zee Entertain': ['ZEEL'],
 'Zensar Tech': ['ZENSARTECH'],
 'Zydus Wellness': ['ZYDUSWELL']}